### ISSUE TITLE
PGP Encryption script

### ISSUE THREAD

**Issue by johnZ-cyber** [qownnotes/scripts#104]
#### Expected behaviour
Decrypt notes only when you click the button to do so

#### Actual behaviour
The PGP encryption script attempts to decrypt the note whenever it is opened, even if not requested by the user.

#### Steps to reproduce
1. Download and activate the mentioned script
2. Encrypt any notes
3. Browse for another note and try to go back to the one that was encrypted
4. Now gpg-agent will request the password-phrase of the key (if it is not unlocked)

#### Additional information
This behavior happens when the private key is protected by a passphrase
Using a key without this protection would solve the problem, but anyway it seems to be an unnecessary use of resources as the QON will decrypt trying to decrypt the note every time it is opened

**Comment by johnZ-cyber** [comment]
btw, the encrypted notes are having this text duplicated (begin/end encrypted text)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
> btw, the encrypted notes are having this text duplicated (begin/end encrypted text)

can you please post an example note

**Comment by pbek** [comment]
> Decrypt notes only when you click the button to do so

Currently it's part of the Note scripting api to try to decrypt the note by default and when the current note is changed the NoteApi will be updated... I'm not sure what will happen in the long run if I remove the decryption part. We'll see...

the way the encryption system with the [encryptionHook](https://docs.qownnotes.org/en/latest/scripting/hooks/#encryptionhook) works is that there will be an attempt made to decrypt a note (with the currently used password, but this script doesn't use that password). If the attempt was successful

**Comment by pbek** [comment]
## 20.8.7
- the note scripting api will now not attempt to automatically decrypt a note in the background because
  this would happen every time the current note changes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by johnZ-cyber** [comment]
Sorry for the delay. 

>There now is a new release, could you please test it and report if it works for you?

Yes, the new update now only decrypts the note when requested, much better! 

> Can you please post an example of an encrypted note. What do you mean by "this text"?

https://i.imgur.com/VLguFt3.png
Text added to an encrypted note with AES-256 encryption (bold) is being accumulated with that generated by openpgp (italic).

****

***

I don't know if this was the previous behavior, but editing when editing an encrypted note and then switching to another note without saving the previous one can result in data loss. Saving the note before going to another note solves this. [video here](https://cryptpad.fr/file/#/2/file/+k6ph9rp3z7h0GpzgdtpTmpz/)

**Comment by pbek** [comment]
> Yes, the new update now only decrypts the note when requested, much better!

thank you for testing

>  Text added to an encrypted note with AES-256 encryption (bold) is being accumulated with that generated by openpgp (italic).

that's ok, the first BEGIN/END is from QOwnNotes to mark an encrypted note, the 2nd is from pgp itself. 

> when editing an encrypted note and then switching to another note without saving the previous one can result in data loss.

I'll look into that.

**Comment by pbek** [comment]
Can you please post the saving issue to https://github.com/pbek/QOwnNotes/issues/

**Comment by johnZ-cyber** [comment]
done. thanks for the support

**Comment by Mahaaveer** [comment]
is it possible to use pgp keys with passphrase protection ? Works well on windows but on Linux, it prompts for password but  decryption ad encryption did not happen.

**Comment by pbek** [comment]
I haven't found a good way to do that... Maybe you can use some external tool to send the password string or use a PGP daemon.
