### ISSUE TITLE
Please share your custom css style sheet with me

### ISSUE THREAD

**Issue by Linuxnoob01** [qownnotes/scripts#105]
I am looking for style sheets CSS before I figure out to make my own.
But can't find any user made css styles

**Comment by pbek** [comment]
Are you talking about style sheets to modify the user interface? I don't think there are any yet, but you can share you if you want. People mostly share their editor color schemata and use https://www.qownnotes.org/scripting/methods-and-objects.html#add-a-custom-stylesheet for fixing things they want to be different.
