### ISSUE TITLE
[Feature Request]  methods to go beginning of note , end of note , start of line , end of line

### ISSUE THREAD

**Issue by v3ss0n** [qownnotes/scripts#112]
Since vim mode can do those , can we get those exposed? 
Or Can we call vim commands supported from the scripting ?
I looked around scripting API and i do not see an api  regarding putting text at specified position in a note.
Should i just select all text and go to end of selection/ start of selection to do ? I think its not effifcient

**Comment by pbek** [comment]
Can you please open a feature request at https://github.com/pbek/QOwnNotes/issues and explain what you want to achieve.

**Comment by v3ss0n** [comment]
Thanks , added : https://github.com/pbek/QOwnNotes/issues/1950
