### ISSUE TITLE
Unchanging note filename when different from headline

### ISSUE THREAD

**Issue by pkeir** [qownnotes/scripts#117]
I use `handleNewNoteHeadlineHook` to create a custom headline, but as I want the file created to have a different name, I also use `handleNoteTextFileNameHook` to avoid spaces in my date-based filename. Alas, `handleNoteTextFileNameHook` is called _each_ time the file gets stored to disk (and so with a new name each time I edit the note). How can I ensure the note file name is assigned only once. Ideally I'd like to assign the headline and the filename together, after "New note", and have no further updates.

I tried calling `currentNote` in `handleNewNoteHeadlineHook`, but it doesn't exist yet. I also tried accessing `note.fullNoteFilePath` in `handleNoteTextFileNameHook`, but it's always empty.

Thanks.

**Comment by pbek** [comment]
At the time `handleNewNoteHeadlineHook` is called the note doesn't exist yet.
Just return the filename you want every time in `handleNoteTextFileNameHook` or is something preventing you from doing that?

**Comment by pbek** [comment]
You could for example check the created date: https://www.qownnotes.org/scripting/classes.html#note

**Comment by pkeir** [comment]
So my `handleNewNoteHeadlineHook` function would have two code paths? In the first instance, I assume there is not yet a file creation date, and so I calculate my string as before using the current time. Subsequently, my `handleNewNoteHeadlineHook`would find that there is a file, and file creation date, and would use that. Does that sound right? (By the way, when I tried a `script.log` containing `note.fileCreated.toISOString()` I get "RangeError: Invalid Date out of range" in both scenarios.)

My hope had been that the `NoteApi` parameter of `handleNewNoteHeadlineHook` would allow access to a boolean indicating that there is already a file name associated with this note. Alternatively, another hook such as `handleNewNoteHeadlineHook`, say `handleNewNoteHeadlineFilenameHook`, could return both a headline and a filename as a simple pair object.

**Comment by pbek** [comment]
Funny, it seems like `fileCreated` will only be set if the note tree is reloaded. But you can also check the `fileLastModified`. But use `handleNoteTextFileNameHook`.

**Comment by pkeir** [comment]
I edited my last comment: my function names were mixed up.

**Comment by pkeir** [comment]
The trouble with `fileLastModified` (unlike the hope with `fileCreated`) is that it always returns a valid date: there is no way to know whether the file already exists. I note that there is a message log output: "Stored current note to disk" after I press the "New note" button. No log message is produced via my script in that situation, so I assume `handleNoteTextFileNameHook` is not being called then - only on subsequent edits of the note do I see my log messages. (It nevertheless names the file as specified by my function!) So I still can't solve my problem.

**Comment by pkeir** [comment]
I added the following at the start of my `handleNoteTextFileNameHook` function, and it seems to be working now. Thanks for the advice.

```javascript
if (!isNaN(note.fileLastModified)) {
  return "";
}
```

**Comment by pbek** [comment]
Great, and I will fix the 'fileCreated'.

**Comment by pbek** [comment]
## 20.12.1
- the `fileCreated` date will now also be set for new note before the note folder is reloaded

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
