### ISSUE TITLE
paste-latex-image: CodeCogs returning "license expired"

### ISSUE THREAD

**Issue by yunesj** [qownnotes/scripts#119]
I think this is an upstream issue. There is a "licensed expired" notice on https://latex.codecogs.com.

```
{"title":"CodeCogs Equation Editor",
"info" : "Expired licence",
"domain": "CLOUD",
"version":"5.8.0.76",
"expiry" : { "year" : 2020"month" : 12"day" : 31}
}
```

@pbek

**Comment by pbek** [comment]
Thank you for reporting. I guess you are talking about https://github.com/qownnotes/scripts/blob/master/paste-latex-image/paste-latex-image.qml.

Do you know if it is possible to use another url instead of http://latex.codecogs.com/gif.latex?

**Comment by pbek** [comment]
It seems their API doesn't "always" seem to work. Just now I was able to get a gif of an equation.

If you find a better API (I didn't find any), please let me know or create a pull request with the changes.

**Comment by yunesj** [comment]
https://latex.codecogs.com/ now says:

```
Registered use: CLOUD
Expiration date: 31-12-2030
```

and the script works for me! Closing...

**Comment by pbek** [comment]
Great, thank you for testing!
