### ISSUE TITLE
in-note-text-tagging using # as tag for compatibility with Epsilon Notes

### ISSUE THREAD

**Issue by marcusyoung** [qownnotes/scripts#130]
#### Script name
in-note-text-tagging
#### Script authors
@Maboroshy 
#### Expected behaviour
Script allows you to specify alternative tag word marker. Epsilon Notes (Android) uses # (in addition to YAML option). So this would be a good alternative to @.
#### Actual behaviour
The script picks up the markdown hashes as tags. For example, ## Heading will identify # as a tag, and ### Heading will identify ## as  a tag. Presumably just needs the regex amending to ignore these.

**Comment by Maboroshy** [comment]
I've updated the script. Please, test if it fixes the issue.

**Comment by marcusyoung** [comment]
This does seem to be fixed now.
