### ISSUE TITLE
Custom new note script now causes application closure

### ISSUE THREAD

**Issue by pkeir** [qownnotes/scripts#142]
The attached script gives a custom name and headline to a new note. The script has worked almost every day for about a year.

Since last week, clicking the "New note" button closes the QOwnNotes application. Opening QOwnNotes again shows the file is there, with the correct custom name, but empty: there is no headline.

I am using version 21.10.9 of QOwnNotes via snap on Ubuntu 20.10.

I enabled logging, and saw that the two main functions in the script return the expected values. The messages that follow, before the application closes, are shown below. (I also tried removing the script, and after that, a new file is created with no problem.)

```
[Oct 19 17:35:04] [debug]: modifyNoteTextFileNameFromQMLHook  - 'newName':  "tue-19-oct-2021-17:35:04-BST"
[Oct 19 17:35:04] [debug]: storing note file:  "tue-19-oct-2021-17:35:04-BST.md"
[Oct 19 17:35:04] [debug]: storeNoteTextFileToDisk  - 'trashItem':  TrashItem: <id>0 <fileName>"Note 2021-10-19T17.35.04.md" <noteSubFolderId>0 <_fullNoteFilePath>"/home/pkeir/docs/my_qownnotes/Note 2021-10-19T17.35.04.md" <relativePath>""
[Oct 19 17:35:04] [debug]: doTrashing  - 'destinationFileName':  "/home/pkeir/docs/my_qownnotes/trash/728"
```

[custom-new-note-headline.qml.txt](https://github.com/qownnotes/scripts/files/7375213/custom-new-note-headline.qml.txt)

**Comment by pbek** [comment]
> The script has worked almost every day for about a year.

On which days didn't it work and why? 😅  Scripts usually don't need days off or get sick. 😁

**Comment by pbek** [comment]
This is a regression introduced in https://github.com/pbek/QOwnNotes/commit/d4c79d6a200e9acb648798fe5840a0ddb508788b.
