### ISSUE TITLE
When importing HTML pages, save absolute links (QOwnNotes)

### ISSUE THREAD

**Issue by develop987** [qownnotes/scripts#143]
#### Expected behavior
 Using the `QOwnNotes Web Companion` extension, I import a page from CHROME.
After importing, I get a note with the text of the page.
I get absolute references in the text.
Link example: `[introduction to C#](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/)`

 
#### Actual behaviour
Using the `QOwnNotes Web Companion` extension, I import a page from CHROME.
After importing, I get a note with the text of the page.
I get relative links in the text.
Example of the link I'm getting now: `[introduction to C#](tutorials/)`

#### Steps to reproduce
CHROME. Right click.
Select **QOwnNotes** > **Send page to QOwnNotes**.
Result: I get a note with the text of the page
![3635](https://user-images.githubusercontent.com/90496895/139542251-5645bc52-f9bb-4a00-a808-a6c97bbd8013.png)

**Comment by pbek** [comment]
Can you please open this feature request in https://github.com/pbek/QOwnNotes/issues, it doesn't have anything to do with scripts, unless you want to write a script for that yourself, which you totally can with https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook.

**Comment by pbek** [comment]
Moved to https://github.com/pbek/QOwnNotes/issues/2285
