### ISSUE TITLE
Script "Paste HTML as GitHub Markdown" is using deprecated markdown_github. Replace with gfm

### ISSUE THREAD

**Issue by Zorziel** [qownnotes/scripts#149]
_Referencing [https://github.com/Zorziel/qownnotes-scripts/issues/1](https://github.com/Zorziel/qownnotes-scripts/issues/1)_

---

#### Script name
[paste-html-as-github-markdown](https://github.com/qownnotes/scripts/tree/master/paste-html-as-github-markdown)

  
#### Script authors
@pbek 
  

#### Expected behaviour
pandoc exports as gfm
  

#### Actual behaviour
pandoc exports as deprecated markdown_github
  

#### Steps to reproduce

1. Add script to QOwnNotes (tested on Windows and Linux (Gentoo), from both the in-app repo and from manually importing the scripts)
    a. Restart QOwnNotes (optional, but I did it anyway)
    b. If you restarted the app, open QOwnNotes and wait for scripts to load
2. Copy selection from any website or application
3. In a Note in QOwnNotes, right-click the editor, go to Custom Actions > Paste HTML as GitHub Markdown
  

#### Output from the debug section in the settings dialog
[QOwnNotes Debug Information.md](https://github.com/qownnotes/scripts/files/7633516/QOwnNotes.Debug.Information.md)

---

# Problem
The original [script](paste-html-as-github-markdown/paste-html-as-github-markdown.qml) calls `markdown_github` as the output/to parameter for pandoc.  According to the [Pandoc](https://github.com/jgm/pandoc#the-universal-markup-converter) project, this option is now deprecated in favor of `gfm` (GitHub Flavored Markdown).

> gfm (GitHub-Flavored Markdown), or the **deprecated and less accurate markdown_github**; use markdown_github only if you need extensions not supported in gfm.

I think we should replace `markdown_github` with `gfm` in [paste-html-as-github-markdown](https://github.com/qownnotes/scripts/tree/master/paste-html-as-github-markdown) instead of creating a new script (like [paste-html-as-github-flavored-markdown](https://github.com/Zorziel/scripts/tree/master/paste-html-as-github-flavored-markdown)) and adding to the repository. 

# Question/Request: 
I would like to submit a pull request to merge my changes here.  However, since I have also added the Paste HTML as GitHub Flavored Markdown to my repo, I am happy to edit it here.  I just didn't want to assume that I had that permission.  So please let me know if I should submit the request or edit or wait for the author to edit it 

---

# Validation, Testing, and Changes
I did multiple tests copying and using "paste-html-as-github-markdown" and "[paste-html-as-github-flavored-markdown](https://github.com/Zorziel/qownnotes-scripts/tree/master/paste-html-as-github-flavored-markdown)" in QOwnNotes from a local script.  For every case that I tested, they are identical.  

## Test 1

For Test1, I tested copying the content of a [Wikipedia page](https://en.wikipedia.org/wiki/Drum_and_bass) and used the plugins in QOwnNotes for both as an example (see https://github.com/Zorziel/qownnotes-scripts/blob/master/paste-html-as-github-flavored-markdown/paste-html-as-github-flavored-markdown.qml for the script): 

### Test Results
- [https://en.wikipedia.org/wiki/Drum_and_bass](https://en.wikipedia.org/wiki/Drum_and_bass) 
  - [test1_gfm.md](https://github.com/Zorziel/scripts/files/7632995/test1_gfm.md)
  - [test1_markdown_github.md](https://github.com/Zorziel/scripts/files/7632996/test1_markdown_github.md)

## Test 2
I edited the original [paste-html-as-github-markdown](https://github.com/Zorziel/scripts/tree/master/paste-html-as-github-markdown) script instead.

### Test Results
- [test2_gfm_in_orig_script.md](https://github.com/Zorziel/qownnotes-scripts/files/7633275/test2_gfm_in_orig_script.md)
- [test2_gfm.md](https://github.com/Zorziel/qownnotes-scripts/files/7633278/test2_gfm.md)
- [test2_markdown_github.md](https://github.com/Zorziel/qownnotes-scripts/files/7633279/test2_markdown_github.md)
#### Misc reference/source
- [zztest2_selection_source.md](https://github.com/Zorziel/qownnotes-scripts/files/7633276/test2_selection_source.md)
- [zztest2_pasteashtml.md](https://github.com/Zorziel/qownnotes-scripts/files/7633277/test2_pasteashtml.md)

So far, aside from filename, I cannot find any differences (I used diff and kdiff3 to diff them).  

All testing results were as expected and there's no difference between the deprecated `markdown_github` and `gfm`.  

# Updated Script
The updated script is available in my fork here: https://github.com/Zorziel/qownnotes-scripts/tree/master/paste-html-as-github-markdown
Alternatively, if we want to just have a new script for gfm, I have also created that here: https://github.com/Zorziel/qownnotes-scripts/tree/master/paste-html-as-github-flavored-markdown

**Comment by pbek** [comment]
Thank you! Please make a pull request.
And please also bump the version number in the `info.json` so users will get an update notification and add yourself as author. 😉

**Comment by pbek** [comment]
If you think there is no use case for the old format just edit the current script. As long as it works on GitHub I'm fine with it.

**Comment by pbek** [comment]
Or even better, you can add a checkbox for the script settings so that users can decide which syntax to use. Default could be the new syntax.

**Comment by Zorziel** [comment]
I'm new to Qt so I'd be more comfortable updating the pandoc call first then work on adding checkboxes for options, including commonmark and other MD outputs that pandoc supports.

**Comment by Zorziel** [comment]
Created pull request #151

**Comment by pbek** [comment]
Great. See https://www.qownnotes.org/scripting/methods-and-objects.html#registering-script-settings-variables for how to add settings to a script.
