### ISSUE TITLE
The Latex code can't display.

### ISSUE THREAD

**Issue by Cat7102** [qownnotes/scripts#154]
I added the Latex Math plugin, and try to type: $x^2$ $\alpha$, but it just shows the blank file icon like this:
![image](https://user-images.githubusercontent.com/35393296/152538576-6a610c93-7020-4fdc-8006-ca25ffe51628.png)

I tried reloading the plugin, but still not work.

The information of the plugin is listed below:
name: Latex Math
version: 0.0.6
author: rO0tr4v3n, Azanel
github link: https://github.com/qownnotes/scripts/tree/master/latex-math

**Comment by pbek** [comment]
You need to mention the authors...
@rO0tr4v3n, @Azanel

**Comment by Cat7102** [comment]
> You need to mention the authors... @r00tr4v3n, @Aganel (you didn't use the `@` any you mistyped both of them) 😅

Thanks! Since the name can't selected, so I used the ocr application and didn't check it. 😅

**Comment by pbek** [comment]
You can even click them.
And you can also copy them from https://github.com/qownnotes/scripts/blob/master/latex-math/info.json#L8 😉 

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by redsigma** [comment]
I have encountering this issue as well. I looked at the right panel of the plugin and scrolled down and i saw it uses `klatexformula` at `/usr/bin/klatexformula`

After i installed it, the files started to appear in `~/.cache/PBE/QOwnNotes/scripts/latex-math/`

**Comment by r00tr4v3n** [comment]
Yes, you might need to change the path to klatexformula (and install it if necessary). That is what the setting should be used for.

**Comment by jwli6** [comment]
@r00tr4v3n hello, latex-math runs wrong on my mac. I set the path to klatexformula correctly, but it still doesn't work. I debugged myself and found that the command generated by the script `bash -c "kalatexformula" -f xxx`; I can generate the file when I run it in the terminal, but the script runs correctly and does not generate the corresponding image file.

**Comment by jwli6** [comment]
And I turned on full access to the disk in qownnotes in the mac settings.

**Comment by jwli6** [comment]
And, its maybe [bug](https://github.com/qownnotes/scripts/blob/9045bcd6eccc5f76a7ab3bcbdee3e51a9e5ad8ee/latex-math/latex-math.qml#L197)? After `regenerateNotePreview`, the previous `noteToMarkdownHtmlHook` will be executed again, and then it will be executed in a loop?

**Comment by jwli6** [comment]
> @r00tr4v3n hello, latex-math runs wrong on my mac. I set the path to klatexformula correctly, but it still doesn't work. I debugged myself and found that the command generated by the script `bash -c "kalatexformula" -f xxx`; I can generate the file when I run it in the terminal, but the script runs correctly and does not generate the corresponding image file.

----
The logs show that it works fine, but it doesn't work
