### ISSUE TITLE
In Text-Highlights script is it possible to highlight in the editor?

### ISSUE THREAD

**Issue by schultzter** [qownnotes/scripts#165]
#### Script name

Text Highlights

#### Script authors

@mleo2003 , @ryliejamesthomas 

#### Expected behaviour

Text in editor is highlighted, and `==` on either side of text greyed like other `**` and `_` markdowns. 

#### Actual behaviour

There does not appear to be any formatting applied. 

![image](https://user-images.githubusercontent.com/30871/160518847-107f89ef-75f5-4bec-b7d7-c4591f3ee976.png)

#### Steps to reproduce

Install the Text Highlights script

Enter the following text in a note: `This is a ==highlight== in the text but this is **bold** and this _italic_ !`

**Comment by pbek** [comment]
You cannot script the editor highlighting, it's far too complex and optimized.

**Comment by schultzter** [comment]
Is it possible to add ==highlight== as a built-in Markdown extension?

**Comment by pbek** [comment]
> Is it possible to add ==highlight== as a built-in Markdown extension?

Why should that be added? 😅

**Comment by pbek** [comment]
I've never seen it in the wild (where have you?) and if so, it even still it doesn't make a lot of sense to implement that into the highlighter, since not even md4c (the html generator for the preview) is supporting it and there already are "bold" and "italic".

**Comment by schultzter** [comment]
Good afternoon

I first saw it in Notejoy but there's also:

   - Typora
   - Obsidian
   - Quilt
   - IA Writer
   - Roam (^^ instead of == though)

Plus you support other non-standard/extensions like strike (~~) and tasks
(- [ ]).

Thanks

-- 
Headed for the second star to the right and straight on 'til morning...

  Eric Schultz

**Comment by ryliejamesthomas** [comment]
> even still it doesn't make a lot of sense to implement that into the highlighter, since not even md4c (the html generator for the preview) is supporting it and there already are "bold" and "italic".

It does render a highlight in the preview.

**Comment by ryliejamesthomas** [comment]
I would also find this useful, as currently I mostly use QON with the preview pane hidden.

**Comment by Beurt** [comment]
> I would also find this useful, as currently I mostly use QON with the preview pane hidden.

You should be able to do it with a very simple script such as this one:

```qml
import QtQml 2.0
import QOwnNotesTypes 1.0

QtObject {

    function init() {
        script.addHighlightingRule("==([^=]*)?==", "", 8, 1, -1);
    }
}
```

Or adding `script.addHighlightingRule("==([^=]*)?==", "", 8, 1, -1);` in the init of https://github.com/qownnotes/scripts/blob/master/text-highlights/text-highlights.qml#L37

**Comment by Beurt** [comment]
I think this issue is closed with https://github.com/qownnotes/scripts/commit/8a48f39afbe11a3c7eb35967e11f414a201aac3b
