### ISSUE TITLE
 latex-math runs wrong on my mac. I set the path to klatexformula correctly, but it still doesn't work. 

### ISSUE THREAD

**Issue by jwli6** [qownnotes/scripts#169]
@r00tr4v3n, @Aganel  hello, latex-math runs wrong on my mac. I set the path to klatexformula correctly, but it still doesn't work. I debugged myself and found that the command generated by the script `bash -c "kalatexformula" -f xxx`; I can generate the file when I run it in the terminal, but the script runs correctly and does not generate the corresponding image file.

_Originally posted by @jwli6 in https://github.com/qownnotes/scripts/issues/154#issuecomment-1153428986_

**Comment by pbek** [comment]
Maybe something with #2299?

**Comment by jwli6** [comment]
Where is #2299? Can you give me a link? Thanks!

**Comment by pbek** [comment]
Ah, sorry. I fixed the link.

**Comment by jwli6** [comment]
Thank u very much! I have checked it, and found that execute `open /bin/bash --args -c xxx` on the terminal, where bash cannot receive arguments, but only `open -a /bin/bash --args -c xxx` can work. In addition, the `--args` parameter of command `open` in macOS12.3.1 has not changed. So how to make `script.startDetachedProcess` execute with `open -a`?

**Comment by pbek** [comment]
> So how to make script.startDetachedProcess execute with open -a

I don't think there currently still is a real solution for https://github.com/pbek/QOwnNotes/issues/2299.

**Comment by jwli6** [comment]
> You could make a pull request to differentiate arguments between operating systems or just modify it in your script folder for a quick fix.
Yes, I downloaded the script file and added the log to debug locally.

> So the image generation works with different parameters?
No, I replaced the print [log](https://github.com/qownnotes/scripts/blob/9045bcd6eccc5f76a7ab3bcbdee3e51a9e5ad8ee/latex-math/latex-math.qml#L214) with `log(\`exec:${exec} param:${param}\`)`, then its output is `exec:zsh param:-c,'"/Applications/klatexformula.app/Contents/MacOS/klatexformula" -f "#RRGGBB" -b "-" --base64arg --preamble="XHVzZXBhY2thZ2V7YW1zbWF0aH1cdXNlcGFja2FnZXthbXNzeW1ifVx1c2VwYWNrYWdle2Ftc2ZvbnRzfQ==" --base64arg --latexinput="XGJmICB4X2kgPSBcZnJhY3sxfXsyfQ==" --dpi 400 --quiet 1 --output /Users/jwli/Library/Caches/PBE/QOwnNotes/scripts/latex-math/34a904272f48aae2fa7b8ce61c157228.png'`.

The whole process did not report any errors, but the latex image could not be displayed, and no image files were seen in the corresponding path/to/scripts/latex-math. I tried to enter the command `zsh -c '"/Applications/klatexformula.app/Contents/MacOS/klatexformula" -f "#RRGGBB" -b "-" --base64arg --preamble="XHVzZXBhY2thZ2V7YW1zbWF0aH1cdXNlcGFja2FnZXthbXNzeW1ifVx1c2VwYWNrYWdle2Ftc2ZvbnRzfQ==" --base64arg --latexinput="XGJmICB4X2kgPSBcZnJhY3sxfXsyfQ==" --dpi 400 --quiet 1 --output /Users/jwli/Library/Caches/PBE/QOwnNotes/scripts/latex-math/34a904272f48aae2fa7b8ce61c157228.png'` in the terminal, and then check that there are corresponding image files in the path/to/scripts/latex-math folder, and the latex images are also displayed normally.
* Why use zsh instead of bash, because I found that the above command on the command line will prompt if bash is used: getcwd cannot access the parent directory: No such file or directory*

**Comment by jwli6** [comment]
Maybe as xx said, let the developer decide how to open other programs?


> > So how to make script.startDetachedProcess execute with open -a
> 
> I don't think there currently still is a real solution for [pbek/QOwnNotes#2299](https://github.com/pbek/QOwnNotes/issues/2299).

Maybe as @ckayr [said](https://github.com/pbek/QOwnNotes/issues/2299#issuecomment-974252955), let the developer decide how to open other programs?

**Comment by jwli6** [comment]
@r00tr4v3n And, do you thinking this is a [bug](https://github.com/qownnotes/scripts/issues/154#issuecomment-1153430674)?

**Comment by r00tr4v3n** [comment]
Could be. I cannot test it though.
