### ISSUE TITLE
how to use: markdown-it script?

### ISSUE THREAD

**Issue by vpistis** [qownnotes/scripts#17]
Hi,

I don't know if it's the right place to make this question :)

I was wondering if there is a setting preference into QOwnNotes for highlight the code and surprising I found the `markdown-it` script.
But after installation nothing changes, the code in preview is still simple black and white, also in html or pdf exported files.
I experiments with parameters but nothing changes.
Where I'm wrong?

I don't know if this is the right place to make this question :)

tx

ciao
vale

**Comment by pbek** [comment]
I'm sorry, if you mean "syntax highlighting all kinds of computer languages" with "highlight the code" then the answer is no, there isn't anything for it yet. Although you could implement your own library as script, if you want to.

**Comment by pbek** [comment]
Note: most existing libraries require JavaScript to be rendered in a browser. QOwnNotes doesn't use a fully fledged browser for the preview.
