### ISSUE TITLE
Tab Sessions

### ISSUE THREAD

**Issue by macsunmood** [qownnotes/scripts#175]
Well.. It works ok for me as for the ver 0.0.2.
What about you, have you tried the latest version, @pbek ?

**Comment by pbek** [comment]
Are we talking about https://github.com/qownnotes/scripts/pull/173#issuecomment-1236270747?

**Comment by macsunmood** [comment]
> Are we talking about [#173 (comment)](https://github.com/qownnotes/scripts/pull/173#issuecomment-1236270747)?

Yes, I guess. You had some issue, which I don't currently have.

**Comment by macsunmood** [comment]
@pbek 
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
seems to work fine. the tag is switched. currently no crashes noticed.

**Comment by macsunmood** [comment]
Great! 
The next step should be adding some custom settings.
