### ISSUE TITLE
Is it possible to add enable script API access to a QCompleter popup?

### ISSUE THREAD

**Issue by Beurt** [qownnotes/scripts#192]
Hi,

As mentioned here <https://github.com/qownnotes/scripts/issues/124#issuecomment-1420499651>, it would be interesting for many present and future plugins to have access to a [QCompleter popup](https://doc.qt.io/qt-5/qcompleter.html#basic-usage) through the script API.

It could let us make some auto-completions scripts (e.g. word auto-completion, note-links auto-completion) or a fast selection of script options (e.g. in the plantUML script allowing users to choose the type of graph to add without fetching the option into a bloated sub-menu).

I really don’t know if or how it could be implemented. But I have ideas of how I could use it.

**Comment by pbek** [comment]
There is https://www.qownnotes.org/scripting/hooks.html#autocompletionhook.

**Comment by Beurt** [comment]
Oh sorry! I missed this one. I think it is the perfect thing we need! I will try to do something with it.
