### ISSUE TITLE
No interface icon in Zotero script (icon svg file not downloaded from Github)

### ISSUE THREAD

**Issue by Beurt** [qownnotes/scripts#194]
It is about the [script Zotero](https://github.com/qownnotes/scripts/tree/master/zotero) I just pushed.

#### Expected behaviour

The [Logo_Zotero.svg](https://github.com/qownnotes/scripts/blob/master/zotero/Logo_Zotero.svg) file should be downloaded and be used in QON interface. Cf. <https://github.com/qownnotes/scripts/blob/65e619fffbe0effe882dc13f51ddf5b617a9b567/zotero/zotero.qml#L67>

#### Actual behaviour

The file is not downloaded to the script directory (`~/.local/share/PBE/QOwnNotes/scripts/zotero/` only contains `zotero.qml`).

Thus, the interface doesn't show the icon.

![Screenshot_20230404_165950](https://user-images.githubusercontent.com/12588136/229834132-7e58cb98-55e4-4eb4-b468-218f70e5e7f2.png)

(it is a vertical toolbar)

#### Steps to reproduce

In Script Parameters, look for `Support for Zotero` script. And install it.

The interface has no Zotero icon, because it has not been downloaded.

#### Relevant log output in the Log panel

```log
[17:10:52] [scripting] loading script file: /home/xxx/.local/share/PBE/QOwnNotes/scripts/zotero/zotero.qml
[17:10:52] [warning] Cannot open file '/home/xxx/.local/share/PBE/QOwnNotes/scripts/zotero/Logo_Zotero.svg', because: No such file or directory
[17:10:52] [warning] Cannot open file '/home/xxx/.local/share/PBE/QOwnNotes/scripts/zotero/Logo_Zotero.svg', because: No such file or directory
```

It is with QON v.23.4.0 Appimage on GNU/Linux (Ubuntu derivative:  KDE NeoN).

**Comment by pbek** [comment]
You are missing this setting: https://github.com/qownnotes/scripts/blob/65e619fffbe0effe882dc13f51ddf5b617a9b567/word-pdf-booklet-export/info.json#L5

**Comment by Beurt** [comment]
Oh sorry! I created a PR to add the setting: <https://github.com/qownnotes/scripts/pull/195>

**Comment by Beurt** [comment]
It works, thank you @pbek !
