### ISSUE TITLE
Script Repository broken

### ISSUE THREAD

**Issue by flexid2000** [qownnotes/scripts#196]
### Actual behaviour

The command *search for scripts in repository* does not show the list of scripts to be installed. It does not show anything.

![screenshot](https://i.imgur.com/pgntmu7.jpg)

### Expected behaviour

The command should show the list.

### Remark

Installing a script manually is still possible.

### QOwnNotes versions

- 23.4.1 OBS build 1026 for Debian Testing
- 23.4.2 AUR build 1027 for Arch Linux

**Comment by mamo2021** [comment]
Same here.
App on Windows 11 and kubuntu 22.04 LTS
The Repository-List keeps beeing empty.

**Comment by pbek** [comment]
@mamo2021, can you please open that issue on https://github.com/pbek/QOwnNotes/issues/new/choose, since it's about the app itself.

**Comment by pbek** [comment]
I can reproduce this finally and opened: https://github.com/pbek/QOwnNotes/issues/2772
