### ISSUE TITLE
Missing library QtQuick.Layouts

### ISSUE THREAD

**Issue by sanderboom** [qownnotes/scripts#197]
#### Script name
Journal-entry

#### Script authors
@pbek, @kantrol and myself

#### Expected behavior
No error. 

#### Actual behavior
Invoking `journalEntryDate` (by clicking the right custom button) which in turn creates a dialog via calendar-window.qml gives an error about `QtQuick.Layouts` not being present. 

Originates here: https://github.com/qownnotes/scripts/blob/c8e289596813632be92384d46f7130c012f1abed/journal-entry/calendar-window.qml#L1

Response of @pbek on telegram, dd 2023-05-10:
> I guess those libraries are not in the disk image, because they are not used by the app.

Platform: macOS arm64.

Leaving this here as issue as more people might encounter this error.

**Comment by pbek** [comment]
Only libraries that are used by QOwnNotes are included in the macOS DMG (or Windows ZIP) by the build pipeline.
I guess those libraries need to be installed by the user (which is much easier on Linux).
