### ISSUE TITLE
Android App & Syncing Available ???

### ISSUE THREAD

**Issue by RayBright** [qownnotes/scripts#198]
I suspect that I could access files through DropBox BUT are you proposing a Android version ???

**Comment by pbek** [comment]
I guess we are talking about https://github.com/pbek/QOwnNotes, right?

The last issue where was talked about that was https://github.com/pbek/QOwnNotes/issues/806.
Nothing much changed since then. Best use Nextcloud and Nextcloud Notes on Android to read your notes.
