### ISSUE TITLE
Rename repository to qownnotes/qownnotes-scripts

### ISSUE THREAD

**Issue by fmakowski** [qownnotes/scripts#2]
Small but very important detail,

I think that renaming the repository to `qownnotes-scripts` or something similar would cause less trouble during cloning or forking. I have already encountered it myself by getting 

    fatal: destination path 'scripts' already exists and is not an empty directory.

Best regards!
Filip

**Comment by pbek** [comment]
Hello Flip, I'm sorry. Such a name is "common practice" (e.g. also by ownCloud and Nextcloud) and you can always checkout a repository with any name you like. Renaming it (I think you can't even rename a GitHub repository) would break the script directory for all current version of QOwnNotes.

**Comment by fmakowski** [comment]
Ok, fair enough, thanks for the explanation! ;)
