### ISSUE TITLE
[BUG] Highlighted text in dark mode is not legible.

### ISSUE THREAD

**Issue by moshpirit** [qownnotes/scripts#204]
#### Script name
Text highlights 

#### Script authors
@mleo2003, @ryliejamesthomas, Beurt 

#### Expected behavior
Change the body text color from white to black, or the opposite color, so even if we select some dark color, a light color is selected for text. Or maybe letting us select the color of the font.
#### Actual behavior
Nothing changes, it just adds a yellow background.

Edit: forgot to add the mentions

**Comment by pbek** [comment]
Best mention the maintainers of the script (with "@"!)

**Comment by Beurt** [comment]
Hi,

Text Highlights scripts allow you to choose which style you want for the highlight.

![Screenshot showing the parameter style of the Text Highlight script](https://github.com/qownnotes/scripts/assets/12588136/7883db7b-b881-4bde-b216-65afe57e75e9)

Then, you are free to set the proper colors in the `Editor fonts & colors` settings of QON

![Screenshot showing the parameters for a specific style in QON](https://github.com/qownnotes/scripts/assets/12588136/500bc65a-a73e-41d1-9a12-fe8fe8623625)

Finally, with the script [Custom note preview styling](https://beurt.github.io/QOwnNoteScriptsList/#custom-stylesheet) you can configure the highlight style for the preview.

![Screenshot showing the custom preview styling script parameters](https://github.com/qownnotes/scripts/assets/12588136/b9c8c72a-e3cd-4ee8-b563-9adda6cdc280)

Is it what you needed?

**Comment by moshpirit** [comment]
Thanks for replying, @Beurt! I appreciate the script, I think it's really cool, I turned it into red, and it looks good in dark themes.

> Then, you are free to set the proper colors in the `Editor fonts & colors` settings of QON

I don't know what you mean exactly by that, in your screenshot, you cannot change the style, it appears as the options are disabled (meaning that we can't change the font, background color, or foreground).

What I meant is that it would be nice to have the script to automatically change the foreground font color, when the background color is very similar, or if not, maybe showing an option to manually change the foreground color of the font. 

I don't know anything about the technical stuff; but maybe it could be achieved by:
- setting the foreground color in the script UI (eg: `#2d2f18`)
- then, in the background, the script makes a copy of the current style by exporting it
- after that, the script would search the foreground color and setting it from its current value to the selected one (eg: `#2d2f18`).

I have even less idea about hexadecimal colors, but the automation of the foreground color, might be easy to achieve by changing the letters "E" or "F" to "0" and vice versa.

**Comment by ryliejamesthomas** [comment]
It's a bit confusing, but to change the styles you have to press 'copy' to create a new schema that can be edited.

**Comment by Beurt** [comment]
Sorry @moshpirit and @ryliejamesthomas but I don't think it is possible to alter styles with a QON Script. You have to do it by hand like I explained in https://github.com/qownnotes/scripts/issues/204#issuecomment-1780524482.
