### ISSUE TITLE
[FEATURE] Color selector menu for text highlighter 

### ISSUE THREAD

**Issue by moshpirit** [qownnotes/scripts#205]
#### Script name
Text highlights 

#### Script authors
@mleo2003, @ryliejamesthomas, Beurt 

#### Expected behavior

It would be nice if the settings let us select the color graphically, maybe with a color menu selector like [PyQt ColorPicker](https://github.com/omega0verride/PyQt-ColorPicker)

#### Actual behavior
We can only include the code of the color.

Edit: thanks for the comment, @pbek, I forgot to add the mentions!

**Comment by pbek** [comment]
Best mention the maintainers of the script (with "@"!)
