### ISSUE TITLE
[SUPPORT] Script to automatically format the Markdown each save

### ISSUE THREAD

**Issue by walking-octopus** [qownnotes/scripts#206]

**Comment by pbek** [comment]
Scripts that automatically alter notes when saving are always dangerous. I would just do that in a custom action with a shortcut you can press, see https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action.

Then you could call an external formatting tool with https://www.qownnotes.org/scripting/methods-and-objects.html#starting-an-external-program-and-wait-for-the-output.
