### ISSUE TITLE
[SUPPORT] Stuck trying to get Backlinks script to work

### ISSUE THREAD

**Issue by fieldrabbit21** [qownnotes/scripts#207]
#### Script name
backlinks
#### Script authors
@dohliam 
#### Question
Hi I'm a newbie with QOwnNotes. I have installed it on Windows. 
I like to work with backlinks. For this I have installed 
1. wiki link support script
2. backlinks script

I am using the WIKI style link format ("[[...]]")

But nothing seems to happen when I open a note that is mentioned in another note.
There is no error.

Anything  that I'm forgetting?
#### Relevant log output in the Log panel
there is no log

**Comment by pbek** [comment]
You need to mention people with an `@` in front of it on GitHub 😉 
so... @dohliam

**Comment by dohliam** [comment]
@fieldrabbit21 If you are using the wikilinks script the backlinks script should "just work" (assuming that the wikilinks themselves are correct).

Are the wikilinks working correctly? In other words, can you click on the link from one article and go to another one as expected?

If so, can you give an example of a working wikilink in your notes (you can create a sample note and then link to it -- it should look something like `[[example]]` or [[test/example]]` if you are using subfolders). Then it should be possible to see if there is an error in the wikilink syntax that might be causing the problem.
