### ISSUE TITLE
[BUG]  Latex Math v0.0.6 script doesn't update pictures when color style is changed

### ISSUE THREAD

**Issue by Popolon** [qownnotes/scripts#209]
#### Script name
Latex Math v0.0.6
#### Script authors
r00tr4v3n, Aganel

#### Expected behavior
image should be rerendered when "formula color" is changed.

#### Actual behavior
When color is changed in "formula color" field, as after changing prefs from light mode to dark mode for example, and changing formula color to #ffffff (white) instead of #000000 (black), the pre-rendered formula is not re-rendered and is so still black. and unreadable. Different formula are well rendered, currently need to remove all corresponding pictures by hand, in the directory.

#### Steps to reproduce
write a formula, for example $x^2$, change the color in the script, delete the formula, rewrite it, the on disk cached image with older colors will still be displayed.

**Comment by pbek** [comment]
@r00tr4v3n, @Aganel

**Comment by r00tr4v3n** [comment]
You could add a settings based hash to the file name when creating the formula or purge the cache on a settings change. I don't see a hook for that though.

**Comment by pbek** [comment]
You could read the settings to check if something has changed: https://www.qownnotes.org/scripting/methods-and-objects.html#loading-application-settings-variables

**Comment by Popolon** [comment]
Trying some html export, I seen, it doesn't follow QOwnNotessettings, and export in black ink on white background.
