### ISSUE TITLE
[FEATURE] Add video display support

### ISSUE THREAD

**Issue by Popolon** [qownnotes/scripts#213]
I don't know if a script should be added for this or if instead it should be a core feature. It is currently not possible to display videos in QOwnNotes as with markdown in browser or some other Markdown note taking tools. Today a mp4 (x264,x265 or av1) file can be very light (<1MB), especially after using ffmpeg a good way to compress or recompress it and/org in note like thumbnail size. It so can be used with screencast etc.

I tried the following syntax, (markdown and HTML5) and none work:

```
 ![Video](media/myvideo.mp4)

<video width="320" height="240" controls>
  <source src="media/myvideo.mp4" type="video/mp4">
</video>
```

When exporting to html.
* The first detect it as mp4 (after given mimetype), but define it as an image: `<p><img src="data:video/mp4;base64,...`
* The second one works fine by putting the mp4 in a `media/` subdir

**Comment by pbek** [comment]
The QTextBrowser, that is used for the Preview, is no fully fledged browser and can't view videos.
