### ISSUE TITLE
[BUG] "exportFolder is not defined" in export-notes-as-website

### ISSUE THREAD

**Issue by denn-moe** [qownnotes/scripts#216]
#### Script name
export-notes-as-website

#### Script authors
@bvn9ne, @dohliam

#### Expected behavior
creation of html files after selecting "export notes as website"

#### Actual behavior
 [warning] file:///home/xxx/.local/share/PBE/QOwnNotes/scripts/export-notes-as-website/export-notes-as-website.qml:71: ReferenceError: exportFolder is not defined

#### Steps to fix the issue
change exportfolder to path in line 71

sorry, should have opened a PR maybe, but still new to this git stuff...

**Comment by dohliam** [comment]
@denn-moe Thanks for the bug report! I can confirm getting the same error on a clean installation of QOwnNotes and the export-notes-as-website script. Should be an easy fix from the looks of it -- will try out your suggestion and can submit the PR for you if it works (with credit to you of course).

**Comment by dohliam** [comment]
This should probably be reopened -- will submit a PR for this when I have some time.
