### ISSUE TITLE
adding favorite note script results with error " Expected a qualified name id"[BUG] 

### ISSUE THREAD

**Issue by joomlafun** [qownnotes/scripts#221]
#### Script name
favorite note
#### Script authors
@pbek 
#### Expected behavior
script loading properly
#### Actual behavior
error There were script errors: file:///home/user/Desktop/Temp/favorite-note.qml:1 Expected a qualified name id 
#### Steps to reproduce
add the script via the script menu
#### Output from the debug section in the settings dialog
logs not relevant as there is an error message and the script cannot get loaded

**Comment by pbek** [comment]
I can't reproduce this issue. I installed the script in the *Script Repository* in QOwnNotes, and was able to create and assign the tag with the button.

**Comment by joomlafun** [comment]
@pbek Have you tried adding the "favorite note script" from the settings>script>add local script, that is where I get the error message.

I could install it manually but I must say that I could not find the script repository of qownnote flatpack

**Comment by pbek** [comment]
Oh, can you please open an issue on https://github.com/flathub/org.qownnotes.QOwnNotes/issues, the flatpak is Community managed. 


So what did you do step by step?

**Comment by joomlafun** [comment]
> Oh, can you please open an issue on https://github.com/flathub/org.qownnotes.QOwnNotes/issues, the flatpak is Community managed.
> 
> So what did you do step by step?

step by step as mentioned : settings>scripting>add local script>load the favorite-note.qml file view the error message in the same scripting tab from the menu

**Comment by pbek** [comment]
How does your `favorite-note.qml` look?

**Comment by joomlafun** [comment]
@pbek 

Sorry my bad I downloaded the qml by doing a save as.. With the .raw file I got it working.

I thought that it would distinguish the bookmared note from other in the listing but it only adds a tag.

Maybe you have already a lot of ongoing feature request but pinning a note at the top of a list or starring(you know mails in a mailbox) would be very helpful for organisation

**Comment by pbek** [comment]
> Or easier, if the title of the note is set as bold, could it show as bold in the note listing?

Hm, it would be very hard to do that, and I don't think it would be advised to actually use different styling in the heading and all that text would get into the note name then too...

But there is a hook where you could modify the note name in the list: https://www.qownnotes.org/scripting/hooks.html#handlenotenamehook

**Comment by joomlafun** [comment]
@pbek 

Thank you for the link. Actually I will just put the note in CAPITAL if it's important; pinning it on top of the list would be great but we can't have it all. 

Have a good day !

**Comment by pbek** [comment]
Have a great day yourself!

Maybe you could create an issue for the empty script repository on the flatpak git repository, like mentioned above?

**Comment by joomlafun** [comment]
@pbek 
Well, I don't really have an issue anymore and I don't think that others do, the situation was due to the fact that I downloaded the script with "save as" instead of downloading the raw code in github.
