### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by Elwood4415** [qownnotes/scripts#223]
#### Script name
Journal Entry
#### Script authors
pbek, sanderboom, kantrol
#### Question
Journal Date button does not return anything
#### Output from the debug section in the settings dialog
see below
#### Relevant log output in the Log panel
see below

#### Expected behaviour

When I click on "Journal Date" button on the Qownnotes toolbar, the journal calendar will open

#### Actual behaviour

When I click on "Journal Date" button on the Qownnotes toolbar, nothing happens

#### Steps to reproduce

Open Qownnotes
Add "Journal Date" button to toolbar
Click on "Journal Date" button
Nothing happens

Incidently, the "Journal" and "Journal Tomorrow" tool buttons work fine

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[20:04:44] [debug] updatePanelMenu - 'updatePanelMenu'
[20:04:44] [debug] currentLocalPath - 'currentLocalPath': "/home/hank/Dropbox/QOwnNotes/Notes"
[20:04:45] [debug] currentLocalPath - 'currentLocalPath': "/home/hank/Dropbox/QOwnNotes/Notes"
[20:05:31] [critical] file:///home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/calendar-window.qml:3 module "QtQuick.Controls" is not installed file:///home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/calendar-window.qml:2 module "QtQuick.Layouts" is not installed file:///home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/calendar-window.qml:3 module "QtQuick.Controls" is not installed file:///home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/calendar-window.qml:2 module "QtQuick.Layouts" is not installed
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Feb 26 20:06:42 2024`
**Version**: `24.2.5`
**Build date**: `Feb 17 2024`
**Build number**: `1082`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 12 (bookworm)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.8`
**Qt Version (runtime)**: `5.15.8`
**Portable mode**: `no`
**Settings path / key**: `/home/hank/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/hank/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Tango`
**Notes in current note folder**: `43`
**Calendar items**: `10`
**Enabled scripts**: `6`

## Server Info

**serverUrl**: `https://liv.nl.tab.digital`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Error transferring https://liv.nl.tab.digital/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Not Found`

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_GB, en_US`
**Language names**: `British English (United Kingdom), American English (United States)`
**Application dictionaries path**: `/home/hank/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/hank/Dropbox/QOwnNotes/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Daily Journal`
**database file**: `/home/hank/Dropbox/QOwnNotes/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://liv.nl.tab.digital`
**username**: `hank@iname.com`
**accountId**: `hank@iname.com`
**Nextcloud Deck boardId**: `2424`
**Nextcloud Deck stackId**: `6717`

### Script `Journal entry`

**id**: `1`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/journal-entry.qml`
**variablesJson**: 
```
{
    "defaultFolder": "Notes/Daily Journal",
    "defaultTags": "journal",
    "noteBodyTemplate": "",
    "singleJournalPerDay": true
}
```
**identifier**: `journal-entry`
**version**: `1.6.0`
**minAppVersion**: `20.4.16`

### Script `Add Multiple tags`

**id**: `2`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/add-multiple-tags/add-multiple-tags.qml`
**variablesJson**: *empty*
**identifier**: `add-multiple-tags`
**version**: `0.0.1`
**minAppVersion**: `17.06.2`

### Script `Weather stats`

**id**: `3`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/weather-stats/weather-stats.qml`
**variablesJson**: *empty*
**identifier**: `weather-stats`
**version**: `0.0.3`
**minAppVersion**: `17.06.4`

### Script `Wiki Links`

**id**: `4`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml`
**variablesJson**: *empty*
**identifier**: `wiki-links`
**version**: `0.0.1`
**minAppVersion**: `20.6.0`

### Script `Backlinks Script`

**id**: `5`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/backlinks/backlinks.qml`
**variablesJson**: *empty*
**identifier**: `backlinks`
**version**: `0.0.1`
**minAppVersion**: `20.4.18`

### Script `Pandoc Export`

**id**: `6`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/pandoc-export/pandoc-export.qml`
**variablesJson**: 
```
{
    "pandocPath": "pandoc"
}
```
**identifier**: `pandoc-export`
**version**: `0.0.1`
**minAppVersion**: `21.12.0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckBoardId** (int): `2424`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `true`
**CloudConnection-1/nextcloudDeckStackId** (int): `6717`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-02-26T19:49:01.299`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Sermons`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10.5,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10.5,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/readonly-mode-allow** (int): `16384`
**NextcloudDeckDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Journal 20240209`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Daily Journal`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 28 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `27`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_journalEntry** (QKeySequence): `Ctrl+Alt+J`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/showDueTodayItemsOnly** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Tasks`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `hc2yVDknN5Fp`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): `/usr/bin/git`
**gitLogCommand** (QString): `%notePath%`
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `gtk2`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `22`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `true`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/hank/Dropbox/QOwnNotes/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Error transferring https://liv.nl.tab.digital/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Not Found`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `/home/hank/Nextcloud/Notes`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2024-02-26T15.49.21, Note 2024-02-23T20.51.36, Note 2024-02-23T18.12.59, Note 2024-02-23T18.06.15`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `true`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShare_note, , actionShow_Todo_List, customAction_journalEntryDate, customAction_journalEntry, customAction_journalEntryTomorrow, customAction_pandocExport`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QStringList): *empty*
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-F6tvFRD8sF4g/name** (QString): `Minimal`
**workspace-F6tvFRD8sF4g/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-F6tvFRD8sF4g/windowState** (QByteArray): `<binary data>`
**workspace-hc2yVDknN5Fp/name** (QString): `Full`
**workspace-hc2yVDknN5Fp/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-hc2yVDknN5Fp/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, F6tvFRD8sF4g, hc2yVDknN5Fp`

## System environment

**QT_SCALE_FACTOR**: `1`
**USER**: `hank`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3213`
**QT_PLATFORMTHEME**: `gtk2`
**HOME**: `/home/hank`
**DESKTOP_SESSION**: `xfce`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**GTK_MODULES**: `canberra-gtk-module:gail:atk-bridge`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/tmp/dbus-HhmqdeMDdd,guid=4789ba320274e53d5adec52565dcd5ca`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**LOGNAME**: `hank`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `1`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**GDM_LANG**: `en_US.UTF-8`
**PAPERSIZE**: `letter`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `xfce-`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SESSION_DESKTOP**: `xfce`
**XAUTHORITY**: `/home/hank/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/hank`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXbvvbFi/agent.3129`
**SHELL**: `/bin/bash`
**GDMSESSION**: `xfce`
**QT_ACCESSIBILITY**: `1`
**QT_LOGGING_RULES**: `qt.qpa.xcb.warning=false`
**XDG_VTNR**: `7`
**PWD**: `/home/hank`
**XDG_DATA_DIRS**: `/usr/share/xfce4:/home/hank/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**QT_PLATFORM_PLUGIN**: `gtk2`
**SESSION_MANAGER**: `local/Lenovo-1:@/tmp/.ICE-unix/3129,unix/Lenovo-1:/tmp/.ICE-unix/3129`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**DISPLAY**: `:0.0`
</details>

**Comment by pbek** [comment]
@sanderboom, @kantrol

**Comment by sanderboom** [comment]
@pbek I think this has come up before. Probably you know best how to deal with missing `QtQuick.Controls` and `QtQuick.Layouts`?

**Comment by Elwood4415** [comment]
> As far as I remember, it was only an issue on windows. On Linux you can just install the missing packages, can't you? 🤷

Thank you for your assistance. Would these packages be the QtQuick.Controls and QtQuick.Layouts? And can I just install them from a package installer?

**Comment by pbek** [comment]
Something like those I'd guess: https://packages.debian.org/search?keywords=qtquick&searchon=names&suite=bookworm&section=all
