### ISSUE TITLE
[BUG] can't export notes as website in any directory path

### ISSUE THREAD

**Issue by ArtjomSchwenk** [qownnotes/scripts#242]
#### Script name
Export notes as website
#### Script authors
@dohliam @bvn9ne
#### Expected behavior
Export all notes as a website into a directory that is created.
#### Actual behavior
No export directory is created and manually setting the export directory doesn't help.
#### Steps to reproduce
Install script from the script repo. Select one or multiple notes, go to scripting, custom actions and select "export notes as website"
### Script `Export notes as website`

**id**: `2`
**path**: `/home/artjom/.local/share/PBE/QOwnNotes/scripts/export-notes-as-website/export-notes-as-website.qml`
**variablesJson**: 
```
{
    "defaultExportFolder": "",
    "exportStyleSelection": "opt1",
    "useAbsolutePaths": false
}
```
**identifier**: `export-notes-as-website`
**version**: `1.1.0`
**minAppVersion**: `22.11.8`

##### Not specifying the export folder:
[warning] file:///home/artjom/.local/share/PBE/QOwnNotes/scripts/export-notes-as-website/export-notes-as-website.qml:71: ReferenceError: exportFolder is not defined

##### specifying export folder name to "debugExport":
[warning] file:///home/artjom/.local/share/PBE/QOwnNotes/scripts/export-notes-as-website/export-notes-as-website.qml:71: ReferenceError: exportFolder is not defined

#### My setup
I use Arch Linux with KDE Plasma 6.2 on Wayland. QOwnNotes is from the AUR and the version is 24.10.2-1

**Comment by pbek** [comment]
Hm, that warning comes from:

https://github.com/qownnotes/scripts/blob/f6e6406ce72cf079693bbcebb0fe16528a21651d/export-notes-as-website/export-notes-as-website.qml#L71

But I don't really understand what went wrong. 🤔

**Comment by pbek** [comment]
Ah, I see. It doesn't look this was ever tested on Linux. 🤔
The `path` variable was not used in:

https://github.com/qownnotes/scripts/blob/f6e6406ce72cf079693bbcebb0fe16528a21651d/export-notes-as-website/export-notes-as-website.qml#L70-L72

I blindly fixed that, can you please update and try to test again?

**Comment by ArtjomSchwenk** [comment]
I updated the script and now it is working. Thank you very much for the quick fix 👍

**Comment by pbek** [comment]
Great, thank you for testing!
