### ISSUE TITLE
[BUG] Outline Numbering sequence is off after 4th heading

### ISSUE THREAD

**Issue by DutchPete** [qownnotes/scripts#248]
#### Script name
Outline Numbering

#### Script authors
@Jerksen 

#### Expected behavior
Correct, sequential/decimal numbering

#### Actual behavior
![QON-bug](https://github.com/user-attachments/assets/3b849615-0533-431b-ac23-4a053b06d691)

Another related issue is I had an empty note with these pre-numbered headings:

![image](https://github.com/user-attachments/assets/cc91fde4-8464-49b0-b3e5-fd357e89d81e)

I then added a new, 3-hash heading:

![image](https://github.com/user-attachments/assets/7d131bbf-d9fe-47d1-b0c9-8dc14e335a5d)

I subsequently ran the script to update outline numbers. This is what I got:

![image](https://github.com/user-attachments/assets/ae0a967c-939e-4f6e-8361-e8e01cde2c01)

#### Steps to reproduce
1. take a note with unnumbered headings and subheadings
2. apply the script

#### Output from the debug section in the settings dialog
The output is 561 lines, which includes everything. Here is the log section relating to the script after running it to get the result in the 1<sup>st</sup> screenshot:

### Script `Outline Numbering`

**id**: `4`
**path**: `/home/user1/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/outline-numbering/outline-numbering.qml`
**variablesJson**: 
```
{
}
```
**identifier**: `outline-numbering`
**version**: `1.0.0`
**minAppVersion**: `20.5.6`

**Comment by DutchPete** [comment]
@pbek : done. My apologies for this oversight.

**Comment by pbek** [comment]
Do you want to work on it? 😉

**Comment by DutchPete** [comment]
Nope, not really. Scripting is not my thing, and even though one can always learn, I have plenty of other things that keep me busy. Sorry.

**Comment by pbek** [comment]
Good job! 😊 
You can post it here. It wouldn't have a maintainer if I would put it in the script repository.

**Comment by DutchPete** [comment]
[outline-numbering.qml.tar.gz](https://github.com/user-attachments/files/18176177/outline-numbering.qml.tar.gz)
