### ISSUE TITLE
export-notes-as-one-html script exports document as ANSI

### ISSUE THREAD

**Issue by piyo-gh** [qownnotes/scripts#25]
I'm using Windows 10 on Japanese locale.
Exported html document by export-notes-as-one-html script says `<meta charset="utf-8"/>`, but document encoding is not utf-8 but ANSI.

This problem doesn't happen when I use `export as HTML`.

**Comment by pbek** [comment]
That's strange, both are using the same method for generating the html.

**Comment by pbek** [comment]
Maybe it's something in https://github.com/pbek/QOwnNotes/blob/7eb1a227a7667bce1c940e6c93d068988bacaf52/src/services/scriptingservice.cpp#L1626-L1639

**Comment by pbek** [comment]
I couldn't reproduce it under Linux, I did get the UTF-8 character set, but now I will distinctly set the character set when writing files, let's see if that fixes the problem for you in 18.03.8.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
