### ISSUE TITLE
PlantUML does not render --> as arrow

### ISSUE THREAD

**Issue by andreas-breitbach** [qownnotes/scripts#27]
Using [render-plantuml](https://github.com/qownnotes/scripts/tree/master/render-plantuml). Expected behaviour with this script would be the rendering as you see in the screenshots. What I get is this Syntax error, which complains that `&gt;`could be wrong. This `&gt;` is the HTML escape code for `>`, which got me thinking that the Markdown (and in turn, the Plantuml-Section), is parsed as HTML (or some other language containing escape codes) at someplace during the rendering. This might as well mix up the Plantuml, making the `>` useless.

Right now I checked if there's anything else in Plantuml, that would be rendered the wrong way - and found some: `"`ends up as `&quot;` (below).

I don't really know how where to go from here/if this might be a bug with render-plantuml, QPlainTextEdit, or Plantuml (which works when started from a command line in the directory with the files, rendering them as it should).

![grafik](https://user-images.githubusercontent.com/20995447/37990043-6bd52a5a-3205-11e8-9c5e-b016bdff2915.png)

**Comment by pbek** [comment]
@nikhilw, something you can take a look at?

**Comment by nikhilw** [comment]
PR raised: #30

**Comment by pbek** [comment]
Great! And I did a version bump of https://github.com/qownnotes/scripts/blob/master/render-plantuml/info.json for you.

**Comment by nikhilw** [comment]
Ah.. yes.. thank you.. :)

**Comment by andreas-breitbach** [comment]
Wonderful :) I'm closing this one. If I stumble upon further render errors, I'll reopen this one.
