### ISSUE TITLE
Proposal: Mandatory OS requerments in script info

### ISSUE THREAD

**Issue by Maboroshy** [qownnotes/scripts#3]
Some complex scripts, like the new Taskwarrior one, don't run on all OSes QOwnNotes run. I propose new mandatory entry "Supported OS" in script info, which can be either "Any desktop OS", a combination of "Windows", "macOS", "Linux", or maybe even "Windows 7" or "Kubuntu" if the script is that special.

The best way is also implementing it on the code level so the app would "grey out" scripts for unsupported platform.

**Comment by pbek** [comment]
Such a thing is on my todo list... But I don't know if we should go above operating systems... I cannot check every version of every software that the client might have installed...

**Comment by Maboroshy** [comment]
I think that code part can be platform only, the rest can go to the description. 
But the "Supported OS" info seen by user should still be mandatory.

**Comment by pbek** [comment]
But why do you think the setting should be mandatory? I planned it to be optional, no setting means it should work on every platform.

**Comment by Maboroshy** [comment]
I mean the text line in script description should be mandatory.

**Comment by pbek** [comment]
So you didn't meant the (to be implemented) array in settings, but an informal text in the description?

**Comment by Maboroshy** [comment]
Yep, but I thought some more about it, and I think your way is better.

**Comment by pbek** [comment]
## 17.06.2
- when posting a script to the *Script repository* you can now define which 
  platforms are supported by the script with the new `platforms` parameter
    - for an example please take a look at
      [info.json](https://github.com/qownnotes/scripts/blob/master/example-script/info.json)
    - this information will be viewed in the *Script repository* dialog
    - if the platform you are running QOwnNotes on is not supported by the script
      the item will be colored grey in the script list of the *Script repository*

@fmakowski, I set `"platforms": ["linux", "macos"]` for your script. Is that ok?

**Comment by fmakowski** [comment]
Sure, I have not yet tested it on mac but I think it should be compatible without any problems.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Works gracefully. 

Taskwarrior script is "greyed out" on my Windows 7 VM, but I still can install it. Maybe there should be some extra "Are you sure dialog?" .

**Comment by pbek** [comment]
Good idea.

**Comment by pbek** [comment]
## 17.06.3
- you can now open the *Script repository dialog* with the Shortcut
  <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>I</kbd>
- if you now try to install a script in the *Script repository* that doesn't 
  support your platform you will get a dialog to cancel the installation
- if you now try to install a script in the *Script repository* that needs a 
  newer version of QOwnNotes you will get a notification to update the application

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
