### ISSUE TITLE
Add due date in taskwarrior script

### ISSUE THREAD

**Issue by bepolymathe** [qownnotes/scripts#34]
Hi @Maboroshy 

Just one question. Is it easy (in your opinion) to add an option to add the due dates in export to taskwarrior via the dedicated script?
I now put my note tasks in the comment section of my YALM header. I configured a keyboard shortcut to "export to taskwarrior", I select the text and shortcut... Taskwarrior is powered and tasks remain marked in their original note.
In addition, this allows me to have them directly in the document without modifying my export (pdf or odt) via Pandoc. The only thing missing at this point is the end date. 

```

---
title: Title of the note
subtile: 
author: 
 - Bepolymathe
date: 2018-06-12
lang: fr 
toc: yes 
abstract: A short text to resume...
tags: Tag1 Tag2
comment : >
	[Note relative](note://Complements notes)
        * A task here +tag
...

```
Thanks in advance for your opinion.

**Comment by Maboroshy** [comment]
I guess you mean adding features the existing "Taskwarrior" script at this repo by @fmakowski. 
The task doesn't look very complex, but the script is. So it depends on your ability to understand script's logic and find that very place to insert few lines making it work for you.

First you need to define a detailed specification of what you want to archive. For me, not being a user of a Taskwarrior script and the app itself, it's not clear enough from your issue.

**Comment by bepolymathe** [comment]
Yes... and sorry, I got the wrong contributor 😲... used to other exchanges on scripts. 

Actually, the script recovers:

> * task two +test

To transform it into :

> task add task two tags:"test"

And I would like him to recover:

> * task two +test due:2d

To transform it into :

> task add task -test due:2d

But I fear that the difficulty comes from the variety of possible formats for the dates in Taskwarrior....

**Comment by Maboroshy** [comment]
What if you'll feed it `task two +test due:2d` or `task two due:2d +test` now? Where will `due:2d` go?

**Comment by bepolymathe** [comment]
If I put 

`task two +test due:2d`

I get a task with the tag "test due:2d"

If I put 

`task two due:2d +test `

I get a task with the title "task two due:2d" but the right tag

**Comment by bepolymathe** [comment]
I'm gonna start getting inspired by things from that side:

```
if (isTask) {
                        var tags = [];
                        taskDescription = isTask[1];
                        logIfVerbose("Detected task: " + taskDescription);
                        var fetchTag;
                        var tagExp = /^(.+)?[\s*]?\+(.+)$/; 
                        var currentTaskDescription = taskDescription;
                        do {
                            logIfVerbose("Fetching tags...");
                            fetchTag = tagExp.exec(currentTaskDescription);
                            if (fetchTag) {
                                logIfVerbose("Tag " + fetchTag[2] + " found!");
                                tags.push(fetchTag[2]);
                                currentTaskDescription = fetchTag[1];
                                var re = new RegExp("\\+" + fetchTag[2].replace(/ /g, ''), "i");
                                taskDescription = taskDescription.replace(re,'');
                            } else
                                break;
} while(currentTaskDescription);
```

**Comment by bepolymathe** [comment]
Grrr... Hard to adapt it.

**Comment by bepolymathe** [comment]
@fmakowski any suggestion ?

**Comment by pbek** [comment]
I will close this issue until there is more information.
