### ISSUE TITLE
Table matrix does not appear

### ISSUE THREAD

**Issue by DutchPete** [qownnotes/scripts#44]
I am using version 18.11.1 on Windows.
A table is not rendered correctly anymore in the preview: the matrix lines around and between the celles do not appear.

#### Expected behaviour
Matrix should appear

#### Actual behaviour
Matrix does NOT appear

#### Steps to reproduce
Make a table

#### Output from the debug section in the settings dialog
Output log is big, what do you need?

**Comment by pbek** [comment]
(Did you mean to post in https://github.com/pbek/QOwnNotes/issues?)

They never did appear. The QTextBrowser of the preview can't render them.

**Comment by pbek** [comment]
See: https://github.com/pbek/QOwnNotes/issues/1018

**Comment by DutchPete** [comment]
> 
> 
> (Did you mean to post in https://github.com/pbek/QOwnNotes/issues?)
> 
> They never did appear. The QTextBrowser of the preview can't render them.

That is definitely not true. I think we may not be talking about the same thing, so let me explain what I mean:

I am referring to the horizontal and vertical lines that delimit the individual cells of a table. This was definitely rendered in previous versions, which I thought was one of the nice features of QON and more elegant than on markdown programs.

**Comment by DutchPete** [comment]
> 
> 
> QTextBrowser never managed to render table borders. Take a look at the link in the other issues. You'll find the supported styles there. Use the "custom preview styling" script from the script repository to enter css styles. If you manage to get borders I will integrate those styles by default.

I am sorry, I am not a coder/programmer so I can't help there.
