### ISSUE TITLE
Line numbering

### ISSUE THREAD

**Issue by DutchPete** [qownnotes/scripts#45]
Is it possible to have line numbering in the Editor panel?

**Comment by pbek** [comment]
No, sorry. Haven't found a good way to do this.

(Did you mean to post in https://github.com/pbek/QOwnNotes/issues?)

**Comment by DutchPete** [comment]
> 
> 
> No, sorry. Haven't found a good way to do this.
> 
> (Did you mean to post in https://github.com/pbek/QOwnNotes/issues?)

Yes, it should have gone there. Sorry.
As for line numbering: many programs. e.g. Notepad++, but others too, offer that feature. Is it that difficult?

**Comment by pbek** [comment]
So far I wasn't able to do that in the QPlainTextEdit reliably and performant... If you find a way please let me know.
