### ISSUE TITLE
@tag and YAML tag scripts wipe out notes

### ISSUE THREAD

**Issue by shankargopal** [qownnotes/scripts#49]
This is for @pbek and @Maboroshy.

### Expected behaviour
I am a new user of QOwnNotes (wonderful, wonderful app!) and tried installing the @tag and YAML tags scripts (separately).  

I tried adding tags in the text of a new note by either typing @tag, or by typing the YAML header.  I also tried adding tags from the menu.

#### Actual behaviour

Typing the tags in the text produced no result.

Adding the tag from the menu wiped out the entire note and replaced it with just an @tag or the YAML tag header.  The tag was added to the tag list, but the notes do not show up when I click on the tag.

#### Steps to reproduce
As above. 
## General Info

**Current Date**: `Sun Jan 6 17:23:45 2019`
**Version**: `19.1.0`
**Build date**: `Jan  1 2019`
**Build number**: `505`
**Platform**: `linux`
**Release**: `OBS`
**Qt Version (build)**: `5.3.2`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `7`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/user/testqnotes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/testqnotes/notes.sqlite`

### Script `Epsilon Notes compatible tags (YAML tags)`

**id**: `1`
**path**: `/home/user/.local/share/scripts/epsilon-notes-tags/epsilon-notes-tags.qml`
**variablesJson**: *empty*
**identifier**: `epsilon-notes-tags`
**version**: `0.0.2`
**minAppVersion**: `18.03.7`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-01-06T17:23:32.753`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 14 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `13`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `15`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/user/testqnotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-01-06T17.20.23, Note 2019-01-06T16.59.02, Note 2019-01-06T16.50.18, Note 2019-01-06T16.46.36`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_SESSION_ID**: `3`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0.0`
**HOME**: `/home/user`
**SESSION_MANAGER**: `local/debian:@/tmp/.ICE-unix/1351,unix/debian:/tmp/.ICE-unix/1351`
**SSH_AGENT_PID**: `1341`
**XDG_SEAT**: `seat0`
**COLORTERM**: `truecolor`
**XDG_MENU_PREFIX**: `xfce-`
**GLADE_MODULE_PATH**: `:`
**XDG_CURRENT_DESKTOP**: `XFCE`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**WINDOWID**: `23068684`
**LOGNAME**: `user`
**GLADE_PIXMAP_PATH**: `:`
**WINDOWPATH**: `7`
**LANG**: `en_US.UTF-8`
**TERM**: `xterm-256color`
**TZ**: `Asia/Kolkata`
**SSH_AUTH_SOCK**: `/tmp/ssh-NmTmo1iUbxVJ/agent.1314`
**XDG_VTNR**: `7`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PWD**: `/home/user/testqnotes/trash`
**DESKTOP_SESSION**: `xfce`
**GLADE_CATALOG_PATH**: `:`
**VTE_VERSION**: `5200`
**USER**: `user`
**PATH**: `/home/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/games`
**SHELL**: `/usr/bin/fizsh`
**XDG_DATA_DIRS**: `/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share`
**SHLVL**: `1`
**OLDPWD**: `/home/user/testqnotes`
**_fizsh_F_DOT_DIR**: `/home/user/.fizsh`
**_fizsh_F_FIZSH**: `fizsh`
**_fizsh_F_EXEC_DIR**: `/usr/bin`
**_fizsh_F_FIZSH_FULL_PATH**: `/usr/bin/fizsh`
**_fizsh_F_BIN_DIR**: `/usr/bin`
**_fizsh_F_ETC_DIR**: `/etc/fizsh`
**_fizsh_F_SYNTAX**: `zsh-syntax-highlighting.zsh`
**_fizsh_F_HIGHLIGHTERS_DIR**: `highlighters`
**_fizsh_F_SEARCH**: `zsh-history-substring-search.zsh`
**_fizsh_F_PROMPT**: `fizsh-prompt.zsh`
**_fizsh_F_FIZSHRC**: `fizshrc.zsh`
**_fizsh_F_MISC**: `fizsh-miscellaneous.zsh`
**_fizsh_F_VERSION_FILE**: `.fizsh-version`
**_fizsh_F_CENTRAL_VERSION**: `1.0.9`
**_fizsh_F_LOCAL_VERSION**: `1.0.9`
**ZDOTDIR**: `/home/user/.fizsh`
**_**: `/usr/bin/QOwnNotes`
**HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE**: *empty*
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:`

#### Relevant log output in the Log panel
Attaching log file created when I added a tag to a note with the YAML script enabled. 

[QOwnNotes.log](https://github.com/qownnotes/scripts/files/2730419/QOwnNotes.log)

**Comment by pbek** [comment]
I'm sorry, I have no experience with the YAML header script, but if you are using it you have at least to enable the setting `allowDifferentNoteFileName` in the *General settings*.

**Comment by shankargopal** [comment]
I wiped the note folder and the settings (using the button in the app), restarted, switched on "Allow note title to be different from file name", installed the script and tried again.  The title of the note remains, but the contents of the note is still wiped.  

Also, as noted, the same behaviour occurs with the @tag script - so it's not only the YAML one.  On my first try I tried the @tag script first and then the YAML one, and this time I did the reverse, and the same error occurred.

**Comment by pbek** [comment]
I've never seen such a thing. Can you please post some example notes?

**Comment by shankargopal** [comment]
I wiped the app database from the settings screen, deleted my notes folder, and restarted QOwnNotes.  With a clean notes folder and a fresh start, I only turned on the setting for allowing title to differ from filename, installed the @tag script, and created a new note like so:

![2019-01-07-113231_1366x768_scrot](https://user-images.githubusercontent.com/1425785/50751612-95c71480-1270-11e9-96fc-cc881293954e.png)

Then I added a tag `Bingo` using the menu, and the note changed to:

![2019-01-07-113305_1366x768_scrot](https://user-images.githubusercontent.com/1425785/50751625-a4153080-1270-11e9-92a9-d4652f702345.png)

Then I added the tag 'Bingo' to one of the built in intro notes, and this is what I got:

![2019-01-07-113333_1366x768_scrot](https://user-images.githubusercontent.com/1425785/50751815-61a02380-1271-11e9-9a5f-7654af92ed02.png)

**Comment by pbek** [comment]
Which scripts are currently turned on? (you can just post that part from the *Debug settings*)

**Comment by pbek** [comment]
And what Linux distro are you using? Debian 8? Your QOwnNotes is built with the very old Qt 5.3.2

**Comment by shankargopal** [comment]
Only this script should be enabled.  This is the output from *Debug settings*:
## Enabled scripts

### Script `@tag tagging in note text (experimental)`

**id**: `1`
**path**: `/home/user/.local/share/scripts/in-note-text-tagging/in-note-text-tagging.qml`
**variablesJson**: 
```
{
    "tagHighlightColor": "purple",
    "tagMarker": "@"
}
```
**identifier**: `in-note-text-tagging`
**version**: `0.0.8`
**minAppVersion**: `17.09.9`

I'm using Debian jessie with testing repositories enabled.  This is the output of `uname -a`:

`Linux debian 4.15.0-2-686-pae #1 SMP Debian 4.15.11-1 (2018-03-20) i686 GNU/Linux`

I installed QOwnNotes from the Debian 8 repository as per the instructions on the site.

**Comment by pbek** [comment]
I'm sorry, I can't reproduce your problem. I added a tag via tagging panel and in the note as text `@test2` and it worked both times without wiping the note.

![image](https://user-images.githubusercontent.com/1798101/50753853-bb91f080-1253-11e9-8baf-1d8375e4feac.png)

**Version**: `19.1.1`
**Build date**: `Jan  7 2019`
**Build number**: `506`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`

**Comment by pbek** [comment]
I see you are using Qt 5.11.3 on Debian... maybe you should try to build QOwnNotes yourself and test if that's the problem (Debian 8 on OBS comes with the original Qt 5.3)

**Comment by shankargopal** [comment]
Sorry for the delay, I was tied up in other work and couldn't get to this. 

You were right!

I didn't build it first - I just tried installing it from the Debian 9 repository instead of the Debian 8 one. And now both @tag and the YAML script seem to work fine (though there's a small delay before any tag entered into the text is recognised).  Thank you for this!

**Comment by pbek** [comment]
> I just tried installing it from the Debian 9 repository instead of the Debian 8 one.

that was an other thing I were going to recommend (beside using the App Image, that currently uses Qt 5.6)

but it still bothers me that there is a problem with the Debian 8 build...

with which version of Qt is the Debian 9.0 version currently built?

> though there's a small delay before any tag entered into the text is recognised)

until the note is stored?

**Comment by shankargopal** [comment]
Sorry again for the delay.  The Qt version for the Debian 9.0 version is 5.7.1. 

The delay is a little longer than that.   The little notice pops up at the bottom saying "Stored 1 note" and then, about half a minute to a minute later, the tag comes up.  I haven't really been able to tell if this is related to anything I do at that time, though.
