### ISSUE TITLE
Feature Request: Adjust the checkbox indent level

### ISSUE THREAD

**Issue by gerroon** [qownnotes/scripts#51]
#### Expected behaviour
The checkboxes render a bit close to the the left of the document

#### Actual behaviour
They render with 1 or 2 indents

#### Steps to reproduce
Enable the "checkbox preview export" script and add the lines below to a markdown doc

```
- [ ] test 1

- [ ] test 2

- [ ] test 3

```

See the screenshot for what is going on.

![screenshot_2019-02-02_19-01-58](https://user-images.githubusercontent.com/8519469/52171152-bb501c80-274f-11e9-9893-272639e519be.png)

EDIT:
Ok never mind, appearantly this script does not rely on the Github markdown checkboxes. One has to remove the dashes 

thanks

**Comment by pbek** [comment]
😄
