### ISSUE TITLE
inbox script cant find python 3 and pandoc locations on the manjaro kde distro

### ISSUE THREAD

**Issue by kyriakosbrastianos** [qownnotes/scripts#61]
QOwnNotes - version 19.5.2 - AUR - build 536
inbox script version 0.2.1

The inbox script can't find python 3 and pandoc location path on the manjaro kde distro even though they are installed.

The errors i get are:
The command/path for pandoc in the script settings is not valid.
Converting web pages to notes will be disabled.

The command/path for Python 3 interpreter in the script settings is not valid.
Please set the correct command/path.

@Maboroshy

**Comment by Maboroshy** [comment]
I'm also using Manjaro KDE. I'll check it out.

**Comment by Maboroshy** [comment]
Got the same thing. Maybe there's something update in Qt so the script stopped working. Will fix.

**Comment by kyriakosbrastianos** [comment]
> Got the same thing. Maybe there's something updated in Qt so the script stopped working. Will fix.

Thank you!

**Comment by kyriakosbrastianos** [comment]
> I'm also using Manjaro KDE. I'll check it out.

Nice to hear. Manjaro KDE is a great distro.

**Comment by Maboroshy** [comment]
I've uploaded the new version that should work. Please, test. The script can still be fragile at times.

**Comment by Maboroshy** [comment]
I close this one for now.
