### ISSUE TITLE
How to create a shortcut?

### ISSUE THREAD

**Issue by sadupl** [qownnotes/scripts#70]
Hello,
I'm new to this app. Can you tell me is there any way I can press a button on keyboard and task will be marked [ x ] ? And when I press again it will be [  ] ?

Regards

**Comment by pbek** [comment]
Are you talking about checkboxes in markdown or actual todo items in the todo list (caldav)?

**Comment by pbek** [comment]
Or about a certain script?

**Comment by sadupl** [comment]
Ok I know. Script settings -> Keyboard Shortcuts and on the bottom there is "Toggle checkbox(es)".

Thank you!

**Comment by pbek** [comment]
Mentioning the script author(s) and the script always helps (see issue template). ;)

Yes, you can set shortcuts for custom actions in the shortcut settings.
I guess that answers your question.
