### ISSUE TITLE
scribble seems to be broken

### ISSUE THREAD

**Issue by bessw** [qownnotes/scripts#71]
#### Expected behaviour
1. template image gets copied to media folder
2. link to image gets inserted in document
3. external editor gets opend with full image path as parameter

#### Actual behaviour
1. ✔️
2. ❓ link gets inserted but looks like this `![scribble](media/4413.png)`, shouldn't there be a "file://"?
3. ❗️ tries to open external editor with `<QOwnNotesInstallDir>/media/4413.png` instead of `<NotesDir>/media/4413.png` as parameter

#### My platform
OS: Win10
QOwnNotes version: 19.10.7

#### problems in code
In [scribble.qml#L63](https://github.com/qownnotes/scripts/blob/8ee0dac6c43f9b4de83f5da8040eeb369bc7a4a4/scribble/scribble.qml#L63) you are calling `insertMediaFile` with `returnUrlOnly` set to true but in the next line you are trying to replace "file://media" which (as far of my understanding) will never match.
@pbek 

When I was trying to fix this I somehow managed to split my note into two saperate ones when running the script🤣, might look into this when im more concentrated.

**Comment by pbek** [comment]
For me the generated `![scribble](media/341084995.png)` works just fine. All your points "Expected behaviour" work for me

>  but in the next line you are trying to replace "file://media" which (as far of my understanding) will never match.

It acts as fallback for the legacy method of linking media files (it was the main method until a few weeks ago).

> question link gets inserted but looks like this ![scribble](media/4413.png), shouldn't there be a "file://"?

not any more (since a few weeks)

**Comment by pbek** [comment]
> external editor gets opend with full image path as parameter

that didn't work, I just ctrl+clicked the image in the editor

**Comment by pbek** [comment]
https://github.com/qownnotes/scripts/blob/8ee0dac6c43f9b4de83f5da8040eeb369bc7a4a4/scribble/scribble.qml#L63 needs to be updated to just prepend the full path of the current note to make the "opening" work again. It would even better to add an option (checkbox) to do it the way the script currently does it (legacy) and the "new" way (with prepending).

Are you up for the task, @bessw? :muscle:

**Comment by bessw** [comment]
I'm not shure what parts of the code you want to be switchable to lagacy version.
But I will try to fix it.

**Comment by pbek** [comment]
Sorry, I previously linked the wrong line in the script, this one is correct: https://github.com/qownnotes/scripts/blob/8ee0dac6c43f9b4de83f5da8040eeb369bc7a4a4/scribble/scribble.qml#L64

The current script works if you enable the "legacy way of inserting links" in the QON settings. In order to be able to open the external application with the correct file the path to the file needs to be generated in a different way.

**Comment by pbek** [comment]
You can do that by using `currentNote().fullNoteFilePath` or playing with the current note folder and note sub-folder path, but I will add a new method `getFileURLFromFileName()` for `NoteApi` to get the absolute file url from a relative file name in the next release.

**Comment by pbek** [comment]
## 19.10.8
- there now is a new method `getFileURLFromFileName()` for `NoteApi` to get the
  absolute file url from a relative file name
    - for more information please take a look at
      [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#note)
- there now is a new property `fullNoteFileDirPath` for `NoteApi` to get the
  absolute directory path of the a note file
    - for more information please take a look at
      [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#note)

**Comment by pbek** [comment]
There now is a new release, you could use `fullNoteFileDirPath` now.

**Comment by pbek** [comment]
And don't forget to bump the `minAppVersion` in https://github.com/qownnotes/scripts/blob/master/scribble/info.json if use are using the new property. :smile:

**Comment by pbek** [comment]
If updated the script now. :smile:  Does it work for you?

**Comment by bessw** [comment]
I've still got problems with it.

First of all since I'm on Windows I needed to add `script.toNativeDirSeparators(mediaFilePath)`.

But the weird thing is for some reason I needed to replace `script.getApplicationSettingsVariable("legacyLinking")` with `false` to test the new behaviour, but when I print `script.getApplicationSettingsVariable("legacyLinking")` to the console it also returns `false` 😕

**Comment by bessw** [comment]
`script.getApplicationSettingsVariable("legacyLinking")` seems to return false as string instead of boolean.

Comparing to `"false"` would fix this here, or is this a bug of `script.getApplicationSettingsVariable("legacyLinking")` and you want to fix it there?

**Comment by pbek** [comment]
> First of all since I'm on Windows I needed to add script.toNativeDirSeparators(mediaFilePath).

great, just add that

> script.getApplicationSettingsVariable("legacyLinking") seems to return false as string instead of boolean.

strange, it worked fine on Linux, `getApplicationSettingsVariable` will return some kind of QVariant, maybe comparing it to a string would be more safe

do you want to create a pull request with the changes?

**Comment by bessw** [comment]
Yes, wait a sec.

**Comment by pbek** [comment]
I bumped the version for you. Can you please check if the script works for your in the script repository.

**Comment by bessw** [comment]
workes ✔️

**Comment by pbek** [comment]
Great! Thank you
