### ISSUE TITLE
Can't get markdown-it running

### ISSUE THREAD

**Issue by bessw** [qownnotes/scripts#72]
#### Expected behaviour
the script initialices without errors

#### Actual behaviour
getting the error `markdown-it.qml:68: TypeError: Type error` [markdown-it.qml#L68](https://github.com/qownnotes/scripts/blob/8ee0dac6c43f9b4de83f5da8040eeb369bc7a4a4/markdown-it/markdown-it.qml#L68)

#### My platform
OS: Win10
QOwnNotes version: 19.10.7
I can remember that a few versions ago, when I tried it last time, it worked.

#### Other observations
```js
function init() {
console.warn("typeof(MarkdownIt)=", typeof(MarkdownIt));
//prints: [warning] typeof(MarkdownIt)= object

console.warn("Object.keys(MarkdownIt)=", Object.keys(MarkdownIt));
//prints: [warning] Object.keys(MarkdownIt)= []
...
```

Seems to me like something has gone wrong with the import, but I haven't realy got a clue maybe you @pbek know what happend.

**Comment by pbek** [comment]
I think that happened with the latest Qt version, one needs to research how to overcome that. Any volunteers?

**Comment by pbek** [comment]
@milan-rusev maybe?

**Comment by pbek** [comment]
Of course @bessw is also welcome. :smiley:

**Comment by bessw** [comment]
I'm new to Qt, don't think thats something for me.

**Comment by bessw** [comment]
I finally found out that the import that should be available with the `MarkdownIt` qualifier is put in `this`.
```js
function init() {
  console.warn("Object.keys(this)= ", Object.keys(this));
  //prints: Object.keys(this)= [markdownit,markdownitDeflist]
  ...
```

**Comment by pbek** [comment]
If you can fix it please make a pull request. :smile_cat:

**Comment by pbek** [comment]
> Now I just fixed it using this.markdownit see (#74).

You really did it. Awesome!

> Please note:

Interesting, thank you!
