### ISSUE TITLE
In Note Text Tagging Counting Behavior and Parsing

### ISSUE THREAD

**Issue by thw26** [qownnotes/scripts#75]
@pbek and @Maboroshy 

#### Expected behaviour

I utilize a tool called jrnl, from https://jrnl.sh. It has in-note text tagging using the '@' sign, as this script makes available. The way that jrnl parses tags is to include only alphanumeric characters and underscores, meaning that if a string contains a period or an apostrophe, the text after the character is excluded. Thus the following tags are understood by jrnl to each be an instance of **test1_test2** and are thus counted together.

* @test1_test2
* @test1_test2's
* @test1_test2.

#### Actual behaviour

This script recognizes **test1_test2**, **test1_test2's**, and **test1_test2.** as separate tags, rather than as natural break points in the tag.

#### Steps to reproduce

* Install QON, install/activate this script.
* Create a note with tag strings containing punctuation characters outside usual alphanumeric characters and underscores.
* Review tags for "duplicate" tag entries.

#### Related behavior

Another related issue to this, from what I can tell, is how QON handles multiple underscore characters in a tag. For instance, in one note, I have written **@Test0_Test1_Test2**. This is interpreted in the live preview to mean that I want the text **Test1** to be underlined, when actually it is a tag consisting of multiple words. The highlighting of the tag name is fine, but the underline in the tag's name is not intended. These are properly recognized as a tag but their live preview is incorrect.

Let me know if I can provide additional information.

**Comment by pbek** [comment]
So what is this issue about? Do you want to write a tagging script that supports the https://jrnl.sh/ tags?

**Comment by thw26** [comment]
The script [in-note-text-tagging](https://github.com/qownnotes/scripts/tree/master/in-note-text-tagging) provides the functionality desired as is. The jrnl program utilizes in-note text tags which are by default prefaced with an `@` character. I believe the functionality of that script can be improved, and I believe that improvement can be found through handling tags like [jrnl](https://github.com/jrnl-org/jrnl) does. Let me take what I have written above and utilize it in another example.

While this system works fine for tags at the top of a file where the tag is separate from the body of the text as below…

foo.txt:
```
@my_family

Today I am writing about my family.
```

That functionality does not work as I would expect if the tag was incorporated into the rest of the text's body. Here are some sample ways that I would utilize tags with jrnl in the text body, not just at the head or foot of the file.

```
Today @my_family went to the store.
```

```
Today is @my_family's fun day.
```

```
Today I spent time with @my_family.
```

In jrnl, these tags would be lumped together as a single tag, `@my_family`. This script's ([in-note-text-tagging](https://github.com/qownnotes/scripts/tree/master/in-note-text-tagging)) functionality currently recognizes three separate tags because of the way it is parsing the punctuation. I believe that the script would be better by changing the way it handles tags to reflect jrnl's implementation of an in-note-text tag.

Hopefully this helps explain! I apologize for any undue confusion. Does that better communicate what the issue is about?

**Comment by pbek** [comment]
That script was only @Maboroshy 's way of implement tagging. So what is it that you need? Help to write your own script?

**Comment by Maboroshy** [comment]
So you want the script to accept only alphanumeric chars and underscore as tags. That is possible. But are there any other rules?

Lets take `@my_family` with alphanumerics and underscore:
`@my_family's` = `@my_family` but
`@my_familys` != `@my_family`
`@my_familys'` != `@my_family`
Right?

`thw26's_family` will be parsed as `thw26` tag, right?

**Comment by Maboroshy** [comment]
Also what about non-latin chars? Like Japanese? Drop'em?

**Comment by Maboroshy** [comment]
I've looked into the code of https://jrnl.sh. It uses `(?u)(?:^|\s)([@][-+*#/\w]+)` Python regex that is ok with unicode stuff. But it won't work "as is" for QML's JS regex engine for unicode.

**Comment by thw26** [comment]
> So you want the script to accept only alphanumeric chars and underscore as tags. That is possible. But are there any other rules?

For my current personal use, yes, as underscores would represent whitespace. Your examples would also be correct, as the idea then would be @my_family and @my_familys and @my_families and @my_fmaily would all be representing something else in written text, or else a typo requiring the user to fix the record.

> I've looked into the code of https://jrnl.sh. It uses (?u)(?:^|\s)([@][-+*#/\w]+) Python regex that is ok with unicode stuff. But it won't work "as is" for QML's JS regex engine for unicode.

For other's reference, [here](https://github.com/jrnl-org/jrnl/blob/master/jrnl/Entry.py) is the link to jrnl's regex.

So to consider converting the regex could be a solution. A more full blown solution would be to detect a user's locale and then utilize an appropriate regex pattern, but this could become a headache for determining multilingual tags.

This [StackOverflow post](https://stackoverflow.com/a/22075070/1896800) describes one set of regex for handling non-Latin words. As one example even for myself, I might in some future scenario need access to U+10380 → U+1039F.

I am familiar with Bash regex. Could we potentially rewrite the given regex in that answer into QML's JS regex for the benefit of non-English and non-Latin languages?

**Comment by Maboroshy** [comment]
You can try out your regexps putting them into this line of the script: https://github.com/qownnotes/scripts/blob/2dea4762dfe8ea04129cb2f8baf0aed72dc60bdd/in-note-text-tagging/in-note-text-tagging.qml#L53

But I remember having lots of pain with QML regexps and unicode that made this line into what it is.

**Comment by aberfan** [comment]
Hello. Hopefully not a super stupid question, but would all that be needed to hardcode a specific pattern be to modify that regexp? 

I have a lot of notes I had in a local wiki, where I have [[Category:X Y Z]], and would like X Y Z to become tags. The in-note tags actually sort of work for this, in that it'll pick up something like [[Category:urls]] as urls]].  

So, if I some how could figure out the regexp, to match "category" and "Category" and "CATEGORY", and ignore any spaces after Category:, is it really just a matter of playing with that single line?

**Comment by Maboroshy** [comment]
Try looking into `epsilon-notes-tags` in this repo. It's much closer to what you want than this script. 

Look into
https://github.com/qownnotes/scripts/blob/2dea4762dfe8ea04129cb2f8baf0aed72dc60bdd/epsilon-notes-tags/epsilon-notes-tags.qml#L47-L53
and 
https://github.com/qownnotes/scripts/blob/2dea4762dfe8ea04129cb2f8baf0aed72dc60bdd/epsilon-notes-tags/epsilon-notes-tags.qml#L119-L129

You could use `i` flag for regexp to make it case insensitive.

**Comment by aberfan** [comment]
Thanks for responding; that other script doesn't show up in qnotes when trying to add scripts from repo; am I doing something wrong? I'm not sure what to modify on it; trying to change the "In Note" one, though, failed spectacularly for me, because I'm clueless.

I tried to do a compromise and just use some character that wouldn't conflict the way # and @ do, but for some reason, not only doesn't qnotes properly display it (displays at <?>) but the script seems to ignore it as well: § <--- This one.  Is there something else I'm doing wrong?  It seems to me it'd be easier just re-tagging with a character going forward, if there's no way to just use the already in-note categories, but I keep slamming up against the wall of my ignorance.

**Comment by Maboroshy** [comment]
The subject script looks for a single tags that has a marker. So you can make it work for your `[[Category:X` syntax if you'd set `[[Category:` as a marker. But it will only get a single tag name after the marker and won't work for a list. 

The Epsilon notes tags script looks for a YAML section (that you don't use), then for a "tag" line in it (that you do use). It gets all the tags in the line. So all you need is to move out the YAML part leaving and tweaking the tag line part for your syntax. Both script are very basic in their logic. You can go through them with a JavaScript documentation and then make a compilation you need.

Adapting a script to a whole different syntax is not as simple as dropping new regexp in. For example, I find parsing the list by splitting much easier than by a regexp. When I think about writing a single regexp that should capture unknown number of tags in a pattern... I doubt many users would try writing such a regexp if I'd make a drop in for it. Also we focus on a `list` part of the script, but there are also `add`, `remove` and `rename` parts.

It's is possible to write some kind of a universal tag syntax constructor script with many options. But it will be much work to write and maintain. There are many corner cases and the user written regexps will misfire a lot causing a stream of issues. I won't step in for the one.

**Comment by aberfan** [comment]
>the tags in the line. So all you need is to move out the YAML part leaving and tweaking the tag line part for your syntax. Both >script are very basic in their logic. You can go through them with a JavaScript documentation and then make a compilation you >need.
Even basic, trying to do any modification turned out to be way over my head, so I'm just using the In Note Text Tagging combined with a silcrow character.   The only problem I seem to have is that it's completely ignored for other note folders.  That is, I have a "Primary" folder, and a "Personal" one, and in Personal, no tags ever are parsed.  They're recognized in the note; they get a highlight there, but nothing shows up in 'tags'. Switching folders to 'Primary' shows all tags in that one.  I've tried reloading the script (and exiting program etc) but I'm assuming this must also be my ignorance and not a bug, so I've just given up on having a separate folder. (I'll note if I try to 'add tag' manually with the button, nothing shows up in the alternate folder either.)

Thank you for adding this script; I really depend on tags to organize notes, and am glad there's some method of keeping them in the notes themselves.

**Comment by Maboroshy** [comment]
That's weird. There's nothing folder related in the script. Maybe something has broken in the tag db of the folder. Try removing the folder from the app, deleting `notes.sqlite` and adding the folder again.

> Thank you for adding this script;

All thanks goes to @pbek who implemented a script based tag handling. The script is a basic logic on top of that.

**Comment by aberfan** [comment]
> That's weird. There's nothing folder related in the script. Maybe something has broken in the tag db of the folder. Try removing the folder from the app, deleting `notes.sqlite` and adding the folder again.

Thank you for the suggestion. I did this, but it didn't matter.   After deleting the notes.sqlite folder in the directory, restarting qnotes, re-adding the folder (checking checkboxes "enable subfolders" and "allow different names", if that matters.), I created a note called "test" with tags (all the height of originality). notes.sqlite is recreated, but using an sql viewer shows it's completely empty, vs the same in the primary folder, where you can see the tags. 
Clicking manually add tags, or typing a tag name that doesn't exist ("Moretest") doesn't create it.

And the log doesn't seem to mention anything useful:
<details>
<summary>Trying to add tag via typing:</summary>

```
[14:02:47] [debug] difference1: Tag: <id>0 <name>"" <parentId>0
[14:02:48] [debug] reloadTagTree - 'noteSubFolderIds': QVector(1)
```
</details>
<details>
<summary>Adding new tag "Moretest" in the note itself:</summary>

```
[14:07:47] [debug] storing note file: "test.md"
[14:07:47] [debug] stored note: Note: <id>1 <name>"test" <fileName>"test.md" <noteSubFolderId>1 <relativePath>"general" <hasDirtyData>false
[14:07:47] [debug] storeUpdatedNotesToDisk - 'count': 1
[14:07:47] [status] Stored 1 note(s) to disk
```
![image](https://user-images.githubusercontent.com/72705523/103178957-15c75a00-484d-11eb-8079-a671f4e257c0.png)
</details>

I couldn't find in the help if setting active note folder is something that should be done for all folders that are being used, or if it's meant for something else; that's the only difference between the primary and personal. They're both under the same top level directory (/pim/primary, /pim/personal), so it's not (presumably) a path issue. 

So again I assume it's just that I'm using this on Windows (and a 'legacy' version at that, W7) and if some day I use this on linux, it'll just work. (And in the interim if I want separate folders, to just do a completely different portable install?)

Regardless, it works if I don't do anything adventurous like different folders, so I'll just stop messing with things I shouldn't and use it as intended! ;)

**Comment by Maboroshy** [comment]
I think `notes.sqlite` should be empty when using this script. I just thought it could be corrupted and break the tagging altogether.

I can't reproduce the issue you have but I think it's not script related. Maybe you should create an issue in the app's github. 

Also I doubt it's a Win 7 issue. I've tested the script on Win 7 when I was writing it and it worked ok. The Qt library the app is based on also still supports Win 7.
