### ISSUE TITLE
yaml front matter

### ISSUE THREAD

**Issue by pihentagy** [qownnotes/scripts#79]
I'd use note tags included to notes, but I'd rather use standard yml front matter to do so.

Could you add an option to use standard yml front matter to your script?

thanks

https://github.com/qownnotes/scripts/blob/master/epsilon-notes-tags/epsilon-notes-tags.qml
@Maboroshy

**Comment by Maboroshy** [comment]
Could you post an example of what you want to use.

**Comment by pihentagy** [comment]
> 
> 
> Could you post an example of what you want to use.

Sure. Like this: https://jekyllrb.com/docs/front-matter/
The only difference is that it is closed by 3 dashes, not 3 periods.

**Comment by Maboroshy** [comment]
Sorry for delay. 

The following test note already works with the script.
```
---
tags: test
---
# Test Note
```
Could you post the test note that reproduces the issue.

**Comment by pihentagy** [comment]
Oh, find, it works, if your yaml front matter ends with dashes.

But if you have an untagged note and you add the first tag to that note, it will create like:
```
---
tags: test
...
# Test Note
```

Yes, I know one can replace the three dots, but it also screws up highlighting in the note, so at least an option would be welcome.

thanks

**Comment by Maboroshy** [comment]
Ok, I'll implement an option for dashes.

**Comment by Maboroshy** [comment]
I've updated the script. Please, test a new option.

**Comment by pihentagy** [comment]
Works like a charm.

I'd articulate the standardness of the new option in the docs. (Could mention Epsilon notes, but the solution is more "general" now :tada:)

I like, that this way, all information is in the markdown files.

Many other markdown editors honour yaml front matter. (see https://jekyllrb.com/docs/front-matter/ for eg.)

**Comment by Maboroshy** [comment]
I'm not sure about "standardness", since YAML spec says to use dots for YAML ending and dashes for separation. But I'll think about updating the docs. Thanks.

**Comment by Maboroshy** [comment]
I've updated the script name and the description. Feel free to make a pull request if you have any ideas how to make it clearer.

**Comment by pihentagy** [comment]
> I'm not sure about "standardness", since YAML spec says to use dots for YAML ending and dashes for separation. But I'll think about updating the docs. Thanks.

Whoops, you are right. Then you can say widespreadness :) Then do we have a display issue with the QOwnNotes editor highlighting?

![image](https://user-images.githubusercontent.com/29916/76627808-fc625500-653b-11ea-8e93-f367db9eab72.png)

**Comment by Maboroshy** [comment]
Yes, I consider we have a highlighting issue with dots. It wasn't there when I implemented the first version of the script.
