### ISSUE TITLE
New script "share by email"

### ISSUE THREAD

**Issue by bepolymathe** [qownnotes/scripts#8]
Hello,

I wrote a little script to share a note by mail using mail application. You just have to click right on the note title and select "share by email". That open your mail application with the note as an attachment. In my case (fedora, thunderbird), it works.
It's a quite basic... maybe you want complete ;)
A pull requests arrive...

**Comment by Maboroshy** [comment]
The script looks like a general "open with" script, maybe it should be positioned more as a general script. Also I propose adding an icon to the button. Maybe it's just me, but I use vertical toolbars, and icon is must for me.

**Comment by bepolymathe** [comment]
You're right. It's like [external note diff](https://github.com/qownnotes/scripts/tree/master/external-note-diff).

**Comment by bepolymathe** [comment]
It's idiot but i don't really understand if i can add the script as a pull request. Maybe i need more than a free plan ?

**Comment by pbek** [comment]
No, you don't need any plan...
Did you read the description on <https://github.com/qownnotes/scripts> yet?

**Comment by bepolymathe** [comment]
Ok... i think i made pull request... right ?

**Comment by Maboroshy** [comment]
I still wonder, if this script is a general "open with" script, as "external note diff", which is already present in the repo, do we need many "open with" scripts with different names and default apps?
Or should we concentrate on telling the user the whole power of a general "open with" script?

**Comment by pbek** [comment]
I asked myself the same question when I create my script... But can all users imagine what you can do with an "open with" script?

**Comment by Maboroshy** [comment]
All users is quite a crowd. Lets limit it to the QON users, which opened a script repo. For now I have the feeling that these users are geeky enough ti understand a command line concept.

If they are not, the chances are high, they don't use Thunderbird, and sending attachment by an Outlook is something like `Outlook.exe /c ipm.note /m youremailadress /a yourfilename.txt`. So these guys are in trouble. I, personally, don't use mail client, so running "share by email" script I'm expecting a pop-up window where to put email addresses.

**Comment by pbek** [comment]
I guess then it should be "share by external email client". Which brings us back to "open notes with" which should be able to open several external programs...

**Comment by bepolymathe** [comment]
I agree. In my mind it was just "open with". This brings us back quite close to the functionality "open with an external editor" which is not a script.
From a user perspective it would be useful to have an "email-sharing" option that uses custom smtp settings (mail box in nextcloud for example ;)) ... but that's another challenge

**Comment by pbek** [comment]
I guess there was no scripting when I did "open with an external editor".

> From a user perspective it would be useful to have an "email-sharing" option that uses custom smtp settings (mail box in nextcloud for example ;))

SMTP is slowly dying... a mail client nowadays has to support a lot of protocols. and there will be no mail-client implemented inside of QOwnNotes ;)

**Comment by bepolymathe** [comment]
Of course. rip smtp ;)

**Comment by Maboroshy** [comment]
I'll close this until script update.
