### ISSUE TITLE
Double click and nested tags in in-note-text-tagging

### ISSUE THREAD

**Issue by r00tr4v3n** [qownnotes/scripts#84]
Awesome application and a very useful script! 
I am looking for a way to make the notes more portable/syncable thus the tags have to be included in the notes themselves. This could be an optional feature to be included in the main app.
#### Expected behaviour
A: Double click in tag panel adds a tag in the note.
B: Adding a tag child adds the entire tag tree e.g. @animals/mammals/wolves
#### Actual behaviour
A: nothing happens
B: just the child tag is added @ wolves

@Maboroshy

**Comment by pbek** [comment]
Best always tag the authors of the script in feature requests.

**Comment by pbek** [comment]
I can provide "A", since it's not script-related, this is a concern of QOwnNotes and the scripting engine itself.

**Comment by r00tr4v3n** [comment]
I see. Thank you, that would be great!

**Comment by pbek** [comment]
## 20.4.12
- when tags in the tag tree are double-clicked now the tag also is added or
  removed via the scripting engine

As for "B", you'll need to ask @Maboroshy, but I don't know if that's in the scope of this script.
But since tagging is scriptable you can always script your own tagging system.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
I've read about your speed, but this... Wow!
Compiling!
As for the script: I guess I have to stick to the main system for now since both scripts (@-tagging and yaml) do not seem to be ready for my personal daily usage yet. I should get familiar with JavaScript and the QON API then :)

**Comment by Maboroshy** [comment]
So do you need the tag tree in the script or not?

**Comment by r00tr4v3n** [comment]
That would be great! I would probably need a few weeks till I can produce something reasonably decent.

**Comment by Maboroshy** [comment]
Most of my code are far from "reasonably decent". :grinning: All I knew was some shell script basics when started writing these scripts.
I'll look into it.

**Comment by r00tr4v3n** [comment]
That is motivating :)
@pbek Doubleclicking with the main tagging system works as expected! Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by r00tr4v3n** [comment]
> So do you need the tag tree in the script or not? Should I get into this or you want to do it yourself and make a pull request?

I got it. I'll better test it a bit in a working environment though.

**Comment by arturolinares** [comment]
Was this ever implemented? I think this would be an awesome feature. Very much like how [Bear handles nested tags](https://bear.app/faq/Tags%20&%20Linking/Nested%20Tags/).

**Comment by pbek** [comment]
https://github.com/qownnotes/scripts/tree/master/yaml-nested-tags may be something for you, @arturolinares.
