### ISSUE TITLE
YAML header tags 

### ISSUE THREAD

**Issue by r00tr4v3n** [qownnotes/scripts#85]
It would be great if the double click tag adding would work on the yaml header. Only the first added tag via the tag panel creates the header. Additional tags are only displayed in the tag panel but not in the header or included in the library.
Is it possible to use nested tags as in the default tag system?

```
---
tags: animals/mammals/wolves biology nature
---
```

https://github.com/qownnotes/scripts/blob/master/epsilon-notes-tags/epsilon-notes-tags.qml
@Maboroshy

**Comment by r00tr4v3n** [comment]
I was digging around in the script and found this:
`[23:17:40] [warning] file:///[...]/epsilon-notes-tags.qml:100: ReferenceError: tagLineStartIndex is not defined`
This is probably the reason why no additional tags can be added.
I don't get why `tagLineMatch` is null if it parses fine for the other iterations of the code?

**Comment by Maboroshy** [comment]
I saw this too while testing your issue. Don't remember this error last time I've updated the script. I'll fix it.

**Comment by r00tr4v3n** [comment]
I think `tagLineStartIndex` and `tagLineEndIndex` should be declared for the function and not locally.

```
                    const tagLineStartIndex = tagLineMatch.index
                    const tagLineEndIndex = tagLineStartIndex + tagLineMatch[0].length
```
[epsilon-notes-tags.qml#L62](https://github.com/qownnotes/scripts/blob/5fe26dca3bbc5e184cad26e60a62f53b32a20cc2/epsilon-notes-tags/epsilon-notes-tags.qml#L62)

This fixes the error for me, I can now add and remove yaml tags via the tag panel.

**Comment by r00tr4v3n** [comment]
As for the nested tags, there would be a lookup function for parent tags needed. Is there an API call besides `script.searchTagsByName("game");` and if not, could you add it? @pbek

**Comment by Maboroshy** [comment]
[Tags are exposed to scripting ](http://docs.qownnotes.org/en/latest/scripting/classes/). There's a property to get the parent tag object and another one to get tag's name.

**Comment by r00tr4v3n** [comment]
How are you guys debugging scripts? Is there a way to get code completion and break points/references in the QtCreator?
I get the feeling that this nested tags feature will get pretty messy if I have to iterate over an entire tag list to get the parents name by id.

A little exercise:
```
        var tagList = []
        note.tags.forEach(function(tag, index, array) {
            script.log(tag)
            if (tag.parentId !== 0)
                tagList.push(tag)
            })
```
Why does this throw a TypeError, isn't `QQmlListProperty` a list/array?

**Comment by Maboroshy** [comment]
I use good old `script.log` all over the place. It will be messy and if you want it to be pulled into original script nested tags should be optional.

As for QQmlListProperty, [looks like it can't do `forEach`](https://bugreports.qt.io/browse/QTBUG-49613). Maybe @pbek knows better.

**Comment by Maboroshy** [comment]
Try a classic loop like:
``` qml 
var i
for (i = 0; i < note.tags.length; i++) {
    script.log(note.tags[i])
}
```

**Comment by r00tr4v3n** [comment]
> Try a classic loop like:

Will try, thank you. 

> I use good old script.log all over the place. It will be messy and if you want it to be pulled into original script nested tags should be optional.

That's what I was afraid of, logs it it. I don't think nested tags are within capabilities yet, I'll try something smaller first. Do you have an idea how to handle the parent search elegantly?

**Comment by pbek** [comment]
> As for the nested tags, there would be a lookup function for parent tags needed. Is there an API call besides script.searchTagsByName("game"); and if not, could you add it?

Can you please make QOwnNotes feature requests and be more specific of what you need.

**Comment by Maboroshy** [comment]
> Do you have an idea how to handle the parent search elegantly?

I'd go with recursive function.
