### ISSUE TITLE
Tags do not filter notes (epsilon-notes-tags)

### ISSUE THREAD

**Issue by r00tr4v3n** [qownnotes/scripts#86]
@Maboroshy 
https://github.com/qownnotes/scripts/tree/master/epsilon-notes-tags

#### Expected behaviour
Notes are filtered by the selected tag(/tags?)

#### Actual behaviour
Nothing

#### Steps to reproduce
- Create a note with yaml tag
```
---
tags: bash
---
```

- reload the folder to update the tags
- see the changed tag counter
- click on the tag

**Comment by Maboroshy** [comment]
Cant' reproduce. Tag filtering doesn't depend on scripting. Valid note counter means the script successfully imported tags. Try creating a new note folder with a few test notes.

**Comment by r00tr4v3n** [comment]
I think it's the subfolders. This test folder reproduces it. 
[test1.zip](https://github.com/qownnotes/scripts/files/4511955/test1.zip)

**Comment by Maboroshy** [comment]
Still not sure what's wrong. Subfolder and tag filters stack in QON. If there's no note with some tag in the selected subfolder note counter for the tag won't show anything. Is there a valid note counter for the tag you want to filter?

**Comment by r00tr4v3n** [comment]
Yes, there are 6 correctly counted notes of 'meeting' in the /sub/sub folders. If I select the root folder, I expect those 6 to show up but they do not.

**Comment by r00tr4v3n** [comment]
This seems to work in the new v20.4.12 :)

**Comment by pbek** [comment]
Ok, so we can close this, right? But 20.4.12 didn't change anything with filtering.
