### ISSUE TITLE
Adapt 'Note link to clipboard' script to insert non-legacy-links

### ISSUE THREAD

**Issue by sanderboom** [qownnotes/scripts#87]
Tagging @Maboroshy (thanks for the script ;))

#### Expected behaviour
When having `Use legacy way to link to notes, images and attachments` set to `false`, insert a new-style-link to the note (relative path).

#### Actual behaviour
Inserts legacy `note://`-style-link.

#### Steps to reproduce
- Make sure `Use legacy way to link to notes, images and attachments` is unchecked
- Enable script 'Note link to clipboard'
- Copy a notelink by right-clicking the note
- Paste link into a note

## Settings
**legacyLinking** (bool): `false`

---

I adapted the script a bit to address this, but hit a problem: there is no way to get the relative link between two notes as the link is constructed on `copy`: https://github.com/qownnotes/scripts/blob/5fe26dca3bbc5e184cad26e60a62f53b32a20cc2/note-link-to-clipboard/note-link-to-clipboard.qml#L14). The note link could of course be pasted in any note. 

Questions:   
- Is there any way transform `note://` to a relative/absolute path on paste?
- Is there a way to link to notes with an absolute path (seems not to be the case)?
- Is there a way to copy a note link (using right mouse click) without opening the note (so no switching notes) but still being able to access the information needed? This would be the most elegant solution IMO, as probably the user didn't want to switch notes anyway. 

Thanks

**Comment by pbek** [comment]
The legacy `note://` links are sub-folder agnostic, you only can have the same note filename once on all sub-folders. And those links are "absolute", the work in all notes.

The non-legacy links work with sub-folders and are relative. You cannot get an absolute link. I don't think this script makes a lot of sense with non-legacy links. What is your use-case for it?

**Comment by pbek** [comment]
Getting relative links to other notes would be possible if I write a bridge to `Note::getFilePathRelativeToNote`, `Note::fileUrlInCurrentNoteFolderToRelativePath` and similar... But again I don't think it makes much sense.

**Comment by sanderboom** [comment]
> But again I don't think it makes much sense.

Yeah that would not be worth it, I agree.

> What is your use-case for it?

Fastest way to get a link to a note that I have in sight right now... it's a nice addition, but could be replaced by 'Insert link...' action.

I assume the answer is no, but just to be sure: is there a way to access note information on right-click on note title, without opening the note (so no switching notes)? 

> You cannot get an absolute link.

Is this a design choice or is there something blocking this?

**Comment by pbek** [comment]
> I assume the answer is no, but just to be sure: is there a way to access note information on right-click on note title, without opening the note (so no switching notes)?

no, I right-click in a tree view selects the item... 

> Is this a design choice or is there something blocking this?

the whole reason for the tremendous effort to rewrite linking along with everything that comes with it was to make it more portable and compatible with other application. those links are by design relative. see: https://github.com/pbek/QOwnNotes/issues/266

**Comment by sanderboom** [comment]
Ok, thanks. It doesn't look like this script will work with new-style-linking in this case. I will abandon the changes to the script and use the 'Insert link' action (when I got my shortcuts back :wink:)

**Comment by pbek** [comment]
Yes, stay with the `note://` links from the script. Why work just fine.
