### ISSUE TITLE
latex-math not working on Mac

### ISSUE THREAD

**Issue by yunesj** [qownnotes/scripts#98]
#### Expected behaviour

Renders latex

#### Actual behaviour

First attempt:

```
Warning: QQmlComponent: Component is not ready ((null):0, (null))
Warning: script errors:  (file:///Users/jeff/Library/Application Support/PBE/QOwnNotes/scripts/latex-math/latex-math.qml:1:1: module "QtQml" version 2.14 is not installed
    import QtQml 2.14
    ^) ((null):0, (null))
```

Changed `import QtQml 2.14` to `import QtQml 2.0`:

```
Warning: QQmlComponent: Component is not ready ((null):0, (null))
Warning: script errors:  (file:///Users/jeff/Library/Application Support/PBE/QOwnNotes/scripts/latex-math/latex-math.qml:3:1: module "QtQuick" is not installed
    import QtQuick 2.0
    ^) ((null):0, (null))
```

Removed `import QtQuick 2.0`:

```
The file /Applications/QOwnNotes.app/Contents/MacOS/bash does not exist.
The file /Applications/QOwnNotes.app/Contents/MacOS/bash does not exist.
```

Replacing `"bash"` with `"/bin/bash"`:

Spawns a bunch of bash windows that don't close, but the bash windows do not try to run the the `klatexformula` command.

Also, I've noticed that the code includes a `execBashDetached(`rm ${workDir}/*`)`, which seems like it could be pretty bad if the config location is left blank, set to the project path, etc.

#### Steps to reproduce

Tried to render `$x^2$`

## General Info

**Current Date**: `Sun May 24 21:55:02 2020`
**Version**: `20.5.10`
**Build date**: `May 18 2020`
**Build number**: `5641`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/jeff/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/jeff/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `8`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/Users/jeff/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/Users/jeff/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: `NYB`
**database file**: `/Users/jeff/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Latex Math`

**id**: `1`
**path**: `/Users/jeff/Library/Application Support/PBE/QOwnNotes/scripts/latex-math/latex-math.qml`
**variablesJson**: 
```
{
    "customPreamble": "\\newcommand{\\mycmd}[1]{\\bf \\underline{#1}}",
    "executable": "/Applications/klatexformula.app/Contents/MacOS/klatexformula",
    "formulaBgColor": "-",
    "formulaColor": "#000000",
    "formulaPrefix": "\\bf ",
    "settingDPI": 600,
    "settingImageSize": 22,
    "usepackages": "amsmath,amssymb,amsfonts",
    "workDir": "/tmp/qon/latex"
}
```
**identifier**: `latex-math`
**version**: `0.0.3`
**minAppVersion**: `20.5.0`

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-10-17T07:27:18.652`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-17T07:27:20.767`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-05-14T20:02:39.180`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**InitialKeyRepeat** (qlonglong): `15`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JMicron External** (QString): `1`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2020-05-24T21:51:10.589`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.SF NS Mono,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,17,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/log-file-cleared** (qlonglong): `1024`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Cell Biotech (BTEC120) Questions`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Learning & Research`
**NoteHistory-1** (QVariantList): `<variant list with 27 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `26`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_latex-math-refresh** (QString): *empty*
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VLI Manufacture String VLI Product String** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/jeff/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `1`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-2HP7tKguZG3v/name** (QString): `Full`
**workspace-2HP7tKguZG3v/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-2HP7tKguZG3v/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 2HP7tKguZG3v`

## System environment

**TERM_PROGRAM**: `Apple_Terminal`
**SHELL**: `/bin/zsh`
**TERM**: `xterm-256color`
**TMPDIR**: `/var/folders/p3/kmmh53_s1r9f4pmzym6k3t_w0000gn/T/`
**TERM_PROGRAM_VERSION**: `433`
**TERM_SESSION_ID**: `4AA5412A-1864-4C20-B4D0-B22E2EEAFA7A`
**USER**: `jeff`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.bOdkjTMrDB/Listeners`
**PATH**: `/usr/local/sbin:/Users/jeff/Scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Users/jeff/Qt/5.14.2/clang_64/bin`
**PWD**: `/Users/jeff/Qt`
**LANG**: `en_US.UTF-8`
**XPC_FLAGS**: `0x0`
**XPC_SERVICE_NAME**: `0`
**SHLVL**: `1`
**HOME**: `/Users/jeff`
**LOGNAME**: `jeff`
**OLDPWD**: `/Users/jeff/Qt`
**QML_IMPORT_PATH**: `/Users/jeff/Qt/5.14.2/clang_64/qml/`
**_**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

**Comment by pbek** [comment]
Can you please mention the authors of the script.

**Comment by yunesj** [comment]
Calling @r00tr4v3n!

**Comment by yunesj** [comment]
Although @pbek, I naively put in a:

```
script.startSynchronousProcess('/usr/bin/touch', ['/tmp/hi']);
```

and it didn't seem to work. Do `startDetachedProcess` and `startSynchronousProcess` work on Mac?

**Comment by r00tr4v3n** [comment]
> and it didn't seem to work. Do `startDetachedProcess` and `startSynchronousProcess` work on Mac?

Maybe I broke those for Mac on the last PR? I'll have a look later.

**Comment by pbek** [comment]
> Do startDetachedProcess and startSynchronousProcess work on Mac?

Yes, they should work.

e.g. `startDetachedProcess` works like that:
https://github.com/pbek/QOwnNotes/blob/da7c23f11062f91c53578c94836cee1b69b18d5d/src/utils/misc.cpp#L401-L437

**Comment by r00tr4v3n** [comment]
> Warning: QQmlComponent: Component is not ready ((null):0, (null))
> Warning: script errors:  (file:///Users/jeff/Library/Application Support/PBE/QOwnNotes/scripts/latex-math/latex-math.qml:1:1: module "QtQml" version 2.14 is not installed
>     import QtQml 2.14
>     ^) ((null):0, (null))

This shouldn't happen in the first place independently from other script API calls.

**Comment by yunesj** [comment]
Hi @r00tr4v3n , why do you think this shouldn't happen, and why do you suggest it's a problem with the Qt version?

Also, what do you think of my comment on the`execBashDetached(rm ${workDir}/*)`, which I think is very risky?

**Comment by r00tr4v3n** [comment]
Since he is complaining about the imports and doesn't even reach the function calls, I suspected it to not be the scripts fault.
Good hint on the rm command. At least directories should be fine though. I could add a file suffix like `rm ${workDir}/*.lat`?

**Comment by yunesj** [comment]
@r00tr4v3n I don't have that problem with the @pbek 's script `paste-latex-image.qml`, which does `import QtQml 2.0` rather than `import QtQml 2.14`.

It seems that all example scripts in the `scripting/examples` use `import QtQml 2.0`.

QOwnNotes seems to be packaged with Qt 5.13.2. According to the QT 5.13.2 documentation, you should use `import QtQml 2.13` if you must use the latest features. 2.14 seems to be an invalid version of QtQml for Qt 5.13.2.

Are you sure you are only using the QtQml version packaged with the QOwnNotes binary, and you aren't using your own QOwnNotes binary with a different version of QtQml, or didn't otherwise alter the import path used by your script during development?

----

As for the `rm` command, I think it would be best to just store the files by default in `~/.cache/latex-math`. If you want to allow a user to specify a different folder, then I think the script should still create a `latex-math` subfolder which you can delete without worry. If you don't like that solution, I think it would still be better to simply warn the user that all of the contents of the given directory will be deleted (and should not be set to `~/Desktop`!

**Comment by r00tr4v3n** [comment]
I might have copied the import version from another script, I can just change it to 2.0.
The default folder would cause problems with Windows users, I'd have to set the defaults according to the operating system.

**Comment by yunesj** [comment]
Yes, I should have said, `[user cache folder]/latex-math`. I think you can get the platform-dependent path via the [QStandardPaths Class](https://doc.qt.io/qt-5/qstandardpaths.html).

My main point was that, _if_ you allow the user to specify the directory, you should either warn the user that its contents will be deleted, or create your own `latex-math` subfolder at the given location.

**Comment by r00tr4v3n** [comment]
A default cache folder might be useful to add to the API. I see what I can get done next week.

**Comment by r00tr4v3n** [comment]
Please have a look at the update, see if it works for you.

**Comment by pbek** [comment]
I will close this issue until there is more information.
